// automatically generated by the FlatBuffers compiler, do not modify

package E2E.Crypto

/**
 * Supported elliptic curves for key exchange
 */
@Suppress("unused")
class Curve private constructor() {
    companion object {
        const val X25519: Byte = 0
        const val Secp256k1: Byte = 1
        const val P256: Byte = 2
    }
}
