// automatically generated by the FlatBuffers compiler, do not modify

package E2E.Crypto

/**
 * Symmetric encryption algorithm
 */
@Suppress("unused")
class EncryptionAlgorithm private constructor() {
    companion object {
        const val AES_256_CTR: Byte = 0
    }
}
