// automatically generated by the FlatBuffers compiler, do not modify

package E2E.Crypto

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

/**
 * A simple payload for testing
 */
@Suppress("unused")
class Payload : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Payload {
        __init(_i, _bb)
        return this
    }
    /**
     * Message content
     */
    val message : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val messageAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(4, 1)
    fun messageInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 4, 1)
    /**
     * Numeric value
     */
    val value : Int
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    /**
     * Binary data
     */
    fun data(j: Int) : UByte {
        val o = __offset(8)
        return if (o != 0) {
            bb.get(__vector(o) + j * 1).toUByte()
        } else {
            0u
        }
    }
    val dataLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    val dataAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(8, 1)
    fun dataInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 8, 1)
    /**
     * Nested messages
     */
    fun nested(j: Int) : E2E.Crypto.Payload? = nested(E2E.Crypto.Payload(), j)
    fun nested(obj: E2E.Crypto.Payload, j: Int) : E2E.Crypto.Payload? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val nestedLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    /**
     * Boolean flag
     */
    val isEncrypted : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_12_19()
        fun getRootAsPayload(_bb: ByteBuffer): Payload = getRootAsPayload(_bb, Payload())
        fun getRootAsPayload(_bb: ByteBuffer, obj: Payload): Payload {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createPayload(builder: FlatBufferBuilder, messageOffset: Int, value: Int, dataOffset: Int, nestedOffset: Int, isEncrypted: Boolean) : Int {
            builder.startTable(5)
            addNested(builder, nestedOffset)
            addData(builder, dataOffset)
            addValue(builder, value)
            addMessage(builder, messageOffset)
            addIsEncrypted(builder, isEncrypted)
            return endPayload(builder)
        }
        fun startPayload(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addMessage(builder: FlatBufferBuilder, message: Int) = builder.addOffset(0, message, 0)
        fun addValue(builder: FlatBufferBuilder, value: Int) = builder.addInt(1, value, 0)
        fun addData(builder: FlatBufferBuilder, data: Int) = builder.addOffset(2, data, 0)
        @kotlin.ExperimentalUnsignedTypes
        fun createDataVector(builder: FlatBufferBuilder, data: UByteArray) : Int {
            builder.startVector(1, data.size, 1)
            for (i in data.size - 1 downTo 0) {
                builder.addByte(data[i].toByte())
            }
            return builder.endVector()
        }
        fun startDataVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(1, numElems, 1)
        fun addNested(builder: FlatBufferBuilder, nested: Int) = builder.addOffset(3, nested, 0)
        fun createNestedVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startNestedVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addIsEncrypted(builder: FlatBufferBuilder, isEncrypted: Boolean) = builder.addBoolean(4, isEncrypted, false)
        fun endPayload(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
