// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace EncryptionTest
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PublicData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static PublicData GetRootAsPublicData(ByteBuffer _bb) { return GetRootAsPublicData(_bb, new PublicData()); }
  public static PublicData GetRootAsPublicData(ByteBuffer _bb, PublicData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PublicData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public string Label { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLabelBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetLabelBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetLabelArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<EncryptionTest.PublicData> CreatePublicData(FlatBufferBuilder builder,
      ulong id = 0,
      StringOffset labelOffset = default(StringOffset)) {
    builder.StartTable(2);
    PublicData.AddId(builder, id);
    PublicData.AddLabel(builder, labelOffset);
    return PublicData.EndPublicData(builder);
  }

  public static void StartPublicData(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddId(FlatBufferBuilder builder, ulong id) { builder.AddUlong(0, id, 0); }
  public static void AddLabel(FlatBufferBuilder builder, StringOffset labelOffset) { builder.AddOffset(1, labelOffset.Value, 0); }
  public static Offset<EncryptionTest.PublicData> EndPublicData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<EncryptionTest.PublicData>(o);
  }
}


static public class PublicDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyString(tablePos, 6 /*Label*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
