// automatically generated by the FlatBuffers compiler, do not modify

package EncryptionV3;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Bag extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_12_19(); }
  public static Bag getRootAsBag(ByteBuffer _bb) { return getRootAsBag(_bb, new Bag()); }
  public static Bag getRootAsBag(ByteBuffer _bb, Bag obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Bag __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  // Field-encryption format 3 walk program of Bag (see FlatbuffersEncryption).
  private static final int[] FLATBUFFERS_ENCRYPTION_PROGRAM = {
    2, 3, 12, 2, 7, 8, 6, 1, 1, 1, 1, 4, 2, 0, 6, 4,
    1, 4
  };
  /**
   * Encrypts, in place, the (encrypted) fields of the Bag buffer that starts at
   * _bb.position(), with field-encryption format 3 (key: 32 bytes; recordIndex:
   * an unsigned 32-bit value, unique per buffer under the key). Throws
   * IllegalArgumentException, before any byte changes, for a bad key or a
   * malformed buffer.
   */
  public static void encryptBuffer(ByteBuffer _bb, byte[] key, int recordIndex) {
    FlatbuffersEncryption.cryptBuffer(_bb, key, recordIndex, FLATBUFFERS_ENCRYPTION_PROGRAM);
  }
  /**
   * Decrypts, in place, the (encrypted) fields of the Bag buffer that starts at
   * _bb.position(), with field-encryption format 3 (key: 32 bytes; recordIndex:
   * an unsigned 32-bit value, unique per buffer under the key). Throws
   * IllegalArgumentException, before any byte changes, for a bad key or a
   * malformed buffer.
   */
  public static void decryptBuffer(ByteBuffer _bb, byte[] key, int recordIndex) {
    FlatbuffersEncryption.cryptBuffer(_bb, key, recordIndex, FLATBUFFERS_ENCRYPTION_PROGRAM);
  }

  public String note() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer noteAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer noteInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public byte itemsType(int j) { int o = __offset(6); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int itemsTypeLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector itemsTypeVector() { return itemsTypeVector(new ByteVector()); }
  public ByteVector itemsTypeVector(ByteVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer itemsTypeAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer itemsTypeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public com.google.flatbuffers.Table items(com.google.flatbuffers.Table obj, int j) { int o = __offset(8); return o != 0 ? __union(obj, __vector(o) + j * 4) : null; }
  public int itemsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public UnionVector itemsVector() { return itemsVector(new UnionVector()); }
  public UnionVector itemsVector(UnionVector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createBag(FlatBufferBuilder builder,
      int noteOffset,
      int itemsTypeOffset,
      int itemsOffset) {
    builder.startTable(3);
    Bag.addItems(builder, itemsOffset);
    Bag.addItemsType(builder, itemsTypeOffset);
    Bag.addNote(builder, noteOffset);
    return Bag.endBag(builder);
  }

  public static void startBag(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addNote(FlatBufferBuilder builder, int noteOffset) { builder.addOffset(0, noteOffset, 0); }
  public static void addItemsType(FlatBufferBuilder builder, int itemsTypeOffset) { builder.addOffset(1, itemsTypeOffset, 0); }
  public static int createItemsTypeVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startItemsTypeVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addItems(FlatBufferBuilder builder, int itemsOffset) { builder.addOffset(2, itemsOffset, 0); }
  public static int createItemsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startItemsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endBag(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishBagBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedBagBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Bag get(int j) { return get(new Bag(), j); }
    public Bag get(Bag obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

