# automatically generated by the FlatBuffers compiler, do not modify

# namespace: EncryptionV3

import flatbuffers
from flatbuffers.compat import import_numpy
from .FlatbuffersEncryption import FlatbuffersEncryption
np = import_numpy()

class Leaf(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Leaf()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLeaf(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Leaf
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Field-encryption format 3 walk program of Leaf (see FlatbuffersEncryption).
    _FLATBUFFERS_ENCRYPTION_PROGRAM = (
        1, 2, 2, 0, 6, 4, 1, 4
    )

    @classmethod
    def EncryptBuffer(cls, buf, key, record_index=0):
        """Returns a copy of a Leaf buffer with its (encrypted) fields
        encrypted with field-encryption format 3 (key: 32 bytes;
        record_index: unique per buffer under the key)."""
        return FlatbuffersEncryption.crypt_buffer(
            buf, key, record_index, cls._FLATBUFFERS_ENCRYPTION_PROGRAM)

    @classmethod
    def DecryptBuffer(cls, buf, key, record_index=0):
        """Returns a copy of a Leaf buffer with its (encrypted) fields
        decrypted with field-encryption format 3 (key: 32 bytes;
        record_index: unique per buffer under the key)."""
        return FlatbuffersEncryption.crypt_buffer(
            buf, key, record_index, cls._FLATBUFFERS_ENCRYPTION_PROGRAM)

    # Leaf
    def Secret(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Leaf
    def Pin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def LeafStart(builder):
    builder.StartObject(2)

def Start(builder):
    LeafStart(builder)

def LeafAddSecret(builder, secret):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(secret), 0)

def AddSecret(builder, secret):
    LeafAddSecret(builder, secret)

def LeafAddPin(builder, pin):
    builder.PrependUint32Slot(1, pin, 0)

def AddPin(builder, pin):
    LeafAddPin(builder, pin)

def LeafEnd(builder):
    return builder.EndObject()

def End(builder):
    return LeafEnd(builder)
