// automatically generated by the FlatBuffers compiler, do not modify

package EncryptionV3;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Leaf extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_12_19(); }
  public static Leaf getRootAsLeaf(ByteBuffer _bb) { return getRootAsLeaf(_bb, new Leaf()); }
  public static Leaf getRootAsLeaf(ByteBuffer _bb, Leaf obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Leaf __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  // Field-encryption format 3 walk program of Leaf (see FlatbuffersEncryption).
  private static final int[] FLATBUFFERS_ENCRYPTION_PROGRAM = {
    1, 2, 2, 0, 6, 4, 1, 4
  };
  /**
   * Encrypts, in place, the (encrypted) fields of the Leaf buffer that starts at
   * _bb.position(), with field-encryption format 3 (key: 32 bytes; recordIndex:
   * an unsigned 32-bit value, unique per buffer under the key). Throws
   * IllegalArgumentException, before any byte changes, for a bad key or a
   * malformed buffer.
   */
  public static void encryptBuffer(ByteBuffer _bb, byte[] key, int recordIndex) {
    FlatbuffersEncryption.cryptBuffer(_bb, key, recordIndex, FLATBUFFERS_ENCRYPTION_PROGRAM);
  }
  /**
   * Decrypts, in place, the (encrypted) fields of the Leaf buffer that starts at
   * _bb.position(), with field-encryption format 3 (key: 32 bytes; recordIndex:
   * an unsigned 32-bit value, unique per buffer under the key). Throws
   * IllegalArgumentException, before any byte changes, for a bad key or a
   * malformed buffer.
   */
  public static void decryptBuffer(ByteBuffer _bb, byte[] key, int recordIndex) {
    FlatbuffersEncryption.cryptBuffer(_bb, key, recordIndex, FLATBUFFERS_ENCRYPTION_PROGRAM);
  }

  public String secret() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer secretAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer secretInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public long pin() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createLeaf(FlatBufferBuilder builder,
      int secretOffset,
      long pin) {
    builder.startTable(2);
    Leaf.addPin(builder, pin);
    Leaf.addSecret(builder, secretOffset);
    return Leaf.endLeaf(builder);
  }

  public static void startLeaf(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addSecret(FlatBufferBuilder builder, int secretOffset) { builder.addOffset(0, secretOffset, 0); }
  public static void addPin(FlatBufferBuilder builder, long pin) { builder.addInt(1, (int) pin, (int) 0L); }
  public static int endLeaf(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Leaf get(int j) { return get(new Leaf(), j); }
    public Leaf get(Leaf obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

