<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace EncryptionV3;

class Level
{
    const Low = 1;
    const High = 2;

    private static $names = array(
        Level::Low=>"Low",
        Level::High=>"High",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
