// automatically generated by the FlatBuffers compiler, do not modify

package EncryptionV3

@Suppress("unused")
class Level private constructor() {
    companion object {
        const val Low: Byte = 1
        const val High: Byte = 2
    }
}
