// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace EncryptionV3
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Node : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static Node GetRootAsNode(ByteBuffer _bb) { return GetRootAsNode(_bb, new Node()); }
  public static Node GetRootAsNode(ByteBuffer _bb, Node obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyNode(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, NodeVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Node __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  // Field-encryption format 3 walk program of Node (see FlatbuffersEncryption).
  private static readonly int[] FlatbuffersEncryptionProgram = {
    2, 3, 50, 15, 2, 22, 1, 4, 30, 0, 5, 32, 0, 0, 14, 2,
    0, 10, 1, 0, 12, 1, 6, 36, 34, 1, 1, 1, 0, 8, 4, 2,
    26, 12, 0, 20, 12, 0, 18, 8, 2, 24, 4, 1, 6, 3, 28, 0,
    16, 8, 2, 0, 6, 4, 1, 4
  };
  /// <summary>
  /// Encrypts, in place, the (encrypted) fields of the Node buffer that starts at
  /// _bb.Position, with field-encryption format 3 (key: 32 bytes; recordIndex:
  /// unique per buffer under the key). Throws ArgumentException, before any
  /// byte changes, for a bad key or a malformed buffer.
  /// </summary>
  public static void EncryptBuffer(ByteBuffer _bb, byte[] key, uint recordIndex) { FlatbuffersEncryption.CryptBuffer(_bb, key, recordIndex, FlatbuffersEncryptionProgram); }
  /// <summary>
  /// Decrypts, in place, the (encrypted) fields of the Node buffer that starts at
  /// _bb.Position, with field-encryption format 3 (key: 32 bytes; recordIndex:
  /// unique per buffer under the key). Throws ArgumentException, before any
  /// byte changes, for a bad key or a malformed buffer.
  /// </summary>
  public static void DecryptBuffer(ByteBuffer _bb, byte[] key, uint recordIndex) { FlatbuffersEncryption.CryptBuffer(_bb, key, recordIndex, FlatbuffersEncryptionProgram); }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public string Secret { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSecretBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetSecretBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetSecretArray() { return __p.__vector_as_array<byte>(6); }
  public uint Pin { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public bool Flag { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public EncryptionV3.Level Level { get { int o = __p.__offset(12); return o != 0 ? (EncryptionV3.Level)__p.bb.GetSbyte(o + __p.bb_pos) : EncryptionV3.Level.Low; } }
  public short Count { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  public long Total { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public double Ratio { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }
  public EncryptionV3.Vec3? Position { get { int o = __p.__offset(20); return o != 0 ? (EncryptionV3.Vec3?)(new EncryptionV3.Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public byte Bytes(int j) { int o = __p.__offset(22); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int BytesLength { get { int o = __p.__offset(22); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBytesBytes() { return __p.__vector_as_span<byte>(22, 1); }
#else
  public ArraySegment<byte>? GetBytesBytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public byte[] GetBytesArray() { return __p.__vector_as_array<byte>(22); }
  public float Readings(int j) { int o = __p.__offset(24); return o != 0 ? __p.bb.GetFloat(__p.__vector(o) + j * 4) : (float)0; }
  public int ReadingsLength { get { int o = __p.__offset(24); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<float> GetReadingsBytes() { return __p.__vector_as_span<float>(24, 4); }
#else
  public ArraySegment<byte>? GetReadingsBytes() { return __p.__vector_as_arraysegment(24); }
#endif
  public float[] GetReadingsArray() { return __p.__vector_as_array<float>(24); }
  public EncryptionV3.Vec3? Points(int j) { int o = __p.__offset(26); return o != 0 ? (EncryptionV3.Vec3?)(new EncryptionV3.Vec3()).__assign(__p.__vector(o) + j * 12, __p.bb) : null; }
  public int PointsLength { get { int o = __p.__offset(26); return o != 0 ? __p.__vector_len(o) : 0; } }
  public string Tags(int j) { int o = __p.__offset(28); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int TagsLength { get { int o = __p.__offset(28); return o != 0 ? __p.__vector_len(o) : 0; } }
  public EncryptionV3.Node? Child { get { int o = __p.__offset(30); return o != 0 ? (EncryptionV3.Node?)(new EncryptionV3.Node()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public EncryptionV3.Node? Children(int j) { int o = __p.__offset(32); return o != 0 ? (EncryptionV3.Node?)(new EncryptionV3.Node()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ChildrenLength { get { int o = __p.__offset(32); return o != 0 ? __p.__vector_len(o) : 0; } }
  public EncryptionV3.Payload PayloadType { get { int o = __p.__offset(34); return o != 0 ? (EncryptionV3.Payload)__p.bb.Get(o + __p.bb_pos) : EncryptionV3.Payload.NONE; } }
  public TTable? Payload<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(36); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public EncryptionV3.Leaf PayloadAsLeaf() { return Payload<EncryptionV3.Leaf>().Value; }
  public uint Plain { get { int o = __p.__offset(38); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static void StartNode(FlatBufferBuilder builder) { builder.StartTable(18); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddSecret(FlatBufferBuilder builder, StringOffset secretOffset) { builder.AddOffset(1, secretOffset.Value, 0); }
  public static void AddPin(FlatBufferBuilder builder, uint pin) { builder.AddUint(2, pin, 0); }
  public static void AddFlag(FlatBufferBuilder builder, bool flag) { builder.AddBool(3, flag, false); }
  public static void AddLevel(FlatBufferBuilder builder, EncryptionV3.Level level) { builder.AddSbyte(4, (sbyte)level, 1); }
  public static void AddCount(FlatBufferBuilder builder, short count) { builder.AddShort(5, count, 0); }
  public static void AddTotal(FlatBufferBuilder builder, long total) { builder.AddLong(6, total, 0); }
  public static void AddRatio(FlatBufferBuilder builder, double ratio) { builder.AddDouble(7, ratio, 0.0); }
  public static void AddPosition(FlatBufferBuilder builder, Offset<EncryptionV3.Vec3> positionOffset) { builder.AddStruct(8, positionOffset.Value, 0); }
  public static void AddBytes(FlatBufferBuilder builder, VectorOffset bytesOffset) { builder.AddOffset(9, bytesOffset.Value, 0); }
  public static VectorOffset CreateBytesVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateBytesVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBytesVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBytesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartBytesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static void AddReadings(FlatBufferBuilder builder, VectorOffset readingsOffset) { builder.AddOffset(10, readingsOffset.Value, 0); }
  public static VectorOffset CreateReadingsVector(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddFloat(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateReadingsVectorBlock(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateReadingsVectorBlock(FlatBufferBuilder builder, ArraySegment<float> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateReadingsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<float>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartReadingsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddPoints(FlatBufferBuilder builder, VectorOffset pointsOffset) { builder.AddOffset(11, pointsOffset.Value, 0); }
  public static void StartPointsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(12, numElems, 4); }
  public static void AddTags(FlatBufferBuilder builder, VectorOffset tagsOffset) { builder.AddOffset(12, tagsOffset.Value, 0); }
  public static VectorOffset CreateTagsVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateTagsVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTagsVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTagsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartTagsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddChild(FlatBufferBuilder builder, Offset<EncryptionV3.Node> childOffset) { builder.AddOffset(13, childOffset.Value, 0); }
  public static void AddChildren(FlatBufferBuilder builder, VectorOffset childrenOffset) { builder.AddOffset(14, childrenOffset.Value, 0); }
  public static VectorOffset CreateChildrenVector(FlatBufferBuilder builder, Offset<EncryptionV3.Node>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateChildrenVectorBlock(FlatBufferBuilder builder, Offset<EncryptionV3.Node>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChildrenVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<EncryptionV3.Node>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChildrenVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<EncryptionV3.Node>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartChildrenVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddPayloadType(FlatBufferBuilder builder, EncryptionV3.Payload payloadType) { builder.AddByte(15, (byte)payloadType, 0); }
  public static void AddPayload(FlatBufferBuilder builder, int payloadOffset) { builder.AddOffset(16, payloadOffset, 0); }
  public static void AddPlain(FlatBufferBuilder builder, uint plain) { builder.AddUint(17, plain, 0); }
  public static Offset<EncryptionV3.Node> EndNode(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<EncryptionV3.Node>(o);
  }
  public static void FinishNodeBuffer(FlatBufferBuilder builder, Offset<EncryptionV3.Node> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedNodeBuffer(FlatBufferBuilder builder, Offset<EncryptionV3.Node> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class NodeVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, false)
      && verifier.VerifyString(tablePos, 6 /*Secret*/, false)
      && verifier.VerifyField(tablePos, 8 /*Pin*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Flag*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 12 /*Level*/, 1 /*EncryptionV3.Level*/, 1, false)
      && verifier.VerifyField(tablePos, 14 /*Count*/, 2 /*short*/, 2, false)
      && verifier.VerifyField(tablePos, 16 /*Total*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 18 /*Ratio*/, 8 /*double*/, 8, false)
      && verifier.VerifyField(tablePos, 20 /*Position*/, 12 /*EncryptionV3.Vec3*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 22 /*Bytes*/, 1 /*byte*/, false)
      && verifier.VerifyVectorOfData(tablePos, 24 /*Readings*/, 4 /*float*/, false)
      && verifier.VerifyVectorOfData(tablePos, 26 /*Points*/, 12 /*EncryptionV3.Vec3*/, false)
      && verifier.VerifyVectorOfStrings(tablePos, 28 /*Tags*/, false)
      && verifier.VerifyTable(tablePos, 30 /*Child*/, EncryptionV3.NodeVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 32 /*Children*/, EncryptionV3.NodeVerify.Verify, false)
      && verifier.VerifyField(tablePos, 34 /*PayloadType*/, 1 /*EncryptionV3.Payload*/, 1, false)
      && verifier.VerifyUnion(tablePos, 34, 36 /*Payload*/, EncryptionV3.PayloadVerify.Verify, false)
      && verifier.VerifyField(tablePos, 38 /*Plain*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
