# automatically generated by the FlatBuffers compiler, do not modify

# namespace: EncryptionV3

import flatbuffers
from flatbuffers.compat import import_numpy
from .FlatbuffersEncryption import FlatbuffersEncryption
np = import_numpy()

class Node(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Node()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Node
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Field-encryption format 3 walk program of Node (see FlatbuffersEncryption).
    _FLATBUFFERS_ENCRYPTION_PROGRAM = (
        2, 3, 50, 15, 2, 22, 1, 4, 30, 0, 5, 32, 0, 0, 14, 2,
        0, 10, 1, 0, 12, 1, 6, 36, 34, 1, 1, 1, 0, 8, 4, 2,
        26, 12, 0, 20, 12, 0, 18, 8, 2, 24, 4, 1, 6, 3, 28, 0,
        16, 8, 2, 0, 6, 4, 1, 4
    )

    @classmethod
    def EncryptBuffer(cls, buf, key, record_index=0):
        """Returns a copy of a Node buffer with its (encrypted) fields
        encrypted with field-encryption format 3 (key: 32 bytes;
        record_index: unique per buffer under the key)."""
        return FlatbuffersEncryption.crypt_buffer(
            buf, key, record_index, cls._FLATBUFFERS_ENCRYPTION_PROGRAM)

    @classmethod
    def DecryptBuffer(cls, buf, key, record_index=0):
        """Returns a copy of a Node buffer with its (encrypted) fields
        decrypted with field-encryption format 3 (key: 32 bytes;
        record_index: unique per buffer under the key)."""
        return FlatbuffersEncryption.crypt_buffer(
            buf, key, record_index, cls._FLATBUFFERS_ENCRYPTION_PROGRAM)

    # Node
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Node
    def Secret(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Node
    def Pin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Node
    def Flag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Node
    def Level(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 1

    # Node
    def Count(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # Node
    def Total(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Node
    def Ratio(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Node
    def Position(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = o + self._tab.Pos
            from EncryptionV3.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Node
    def Bytes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Node
    def BytesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Node
    def BytesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Node
    def BytesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # Node
    def Readings(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Node
    def ReadingsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Node
    def ReadingsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Node
    def ReadingsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

    # Node
    def Points(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            from EncryptionV3.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Node
    def PointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Node
    def PointsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        return o == 0

    # Node
    def Tags(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # Node
    def TagsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Node
    def TagsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        return o == 0

    # Node
    def Child(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from EncryptionV3.Node import Node
            obj = Node()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Node
    def Children(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from EncryptionV3.Node import Node
            obj = Node()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Node
    def ChildrenLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Node
    def ChildrenIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        return o == 0

    # Node
    def PayloadType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Node
    def Payload(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # Node
    def Plain(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def NodeStart(builder):
    builder.StartObject(18)

def Start(builder):
    NodeStart(builder)

def NodeAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    NodeAddName(builder, name)

def NodeAddSecret(builder, secret):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(secret), 0)

def AddSecret(builder, secret):
    NodeAddSecret(builder, secret)

def NodeAddPin(builder, pin):
    builder.PrependUint32Slot(2, pin, 0)

def AddPin(builder, pin):
    NodeAddPin(builder, pin)

def NodeAddFlag(builder, flag):
    builder.PrependBoolSlot(3, flag, 0)

def AddFlag(builder, flag):
    NodeAddFlag(builder, flag)

def NodeAddLevel(builder, level):
    builder.PrependInt8Slot(4, level, 1)

def AddLevel(builder, level):
    NodeAddLevel(builder, level)

def NodeAddCount(builder, count):
    builder.PrependInt16Slot(5, count, 0)

def AddCount(builder, count):
    NodeAddCount(builder, count)

def NodeAddTotal(builder, total):
    builder.PrependInt64Slot(6, total, 0)

def AddTotal(builder, total):
    NodeAddTotal(builder, total)

def NodeAddRatio(builder, ratio):
    builder.PrependFloat64Slot(7, ratio, 0.0)

def AddRatio(builder, ratio):
    NodeAddRatio(builder, ratio)

def NodeAddPosition(builder, position):
    builder.PrependStructSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(position), 0)

def AddPosition(builder, position):
    NodeAddPosition(builder, position)

def NodeAddBytes(builder, bytes):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(bytes), 0)

def AddBytes(builder, bytes):
    NodeAddBytes(builder, bytes)

def NodeStartBytesVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartBytesVector(builder, numElems):
    return NodeStartBytesVector(builder, numElems)

def NodeCreateBytesVector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependUint8(item)
    return builder.EndVector()

def CreateBytesVector(builder, data):
    return NodeCreateBytesVector(builder, data)

def NodeAddReadings(builder, readings):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(readings), 0)

def AddReadings(builder, readings):
    NodeAddReadings(builder, readings)

def NodeStartReadingsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartReadingsVector(builder, numElems):
    return NodeStartReadingsVector(builder, numElems)

def NodeCreateReadingsVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependFloat32(item)
    return builder.EndVector()

def CreateReadingsVector(builder, data):
    return NodeCreateReadingsVector(builder, data)

def NodeAddPoints(builder, points):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(points), 0)

def AddPoints(builder, points):
    NodeAddPoints(builder, points)

def NodeStartPointsVector(builder, numElems):
    return builder.StartVector(12, numElems, 4)

def StartPointsVector(builder, numElems):
    return NodeStartPointsVector(builder, numElems)

def NodeCreatePointsVector(builder, data):
    data = list(data)
    builder.StartVector(12, len(data), 4)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def CreatePointsVector(builder, data):
    return NodeCreatePointsVector(builder, data)

def NodeAddTags(builder, tags):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(tags), 0)

def AddTags(builder, tags):
    NodeAddTags(builder, tags)

def NodeStartTagsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTagsVector(builder, numElems):
    return NodeStartTagsVector(builder, numElems)

def NodeCreateTagsVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateTagsVector(builder, data):
    return NodeCreateTagsVector(builder, data)

def NodeAddChild(builder, child):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(child), 0)

def AddChild(builder, child):
    NodeAddChild(builder, child)

def NodeAddChildren(builder, children):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(children), 0)

def AddChildren(builder, children):
    NodeAddChildren(builder, children)

def NodeStartChildrenVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartChildrenVector(builder, numElems):
    return NodeStartChildrenVector(builder, numElems)

def NodeCreateChildrenVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateChildrenVector(builder, data):
    return NodeCreateChildrenVector(builder, data)

def NodeAddPayloadType(builder, payloadType):
    builder.PrependUint8Slot(15, payloadType, 0)

def AddPayloadType(builder, payloadType):
    NodeAddPayloadType(builder, payloadType)

def NodeAddPayload(builder, payload):
    builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)

def AddPayload(builder, payload):
    NodeAddPayload(builder, payload)

def NodeAddPlain(builder, plain):
    builder.PrependUint32Slot(17, plain, 0)

def AddPlain(builder, plain):
    NodeAddPlain(builder, plain)

def NodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return NodeEnd(builder)
