// automatically generated by the FlatBuffers compiler, do not modify

package EncryptionV3;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Node extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_12_19(); }
  public static Node getRootAsNode(ByteBuffer _bb) { return getRootAsNode(_bb, new Node()); }
  public static Node getRootAsNode(ByteBuffer _bb, Node obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Node __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  // Field-encryption format 3 walk program of Node (see FlatbuffersEncryption).
  private static final int[] FLATBUFFERS_ENCRYPTION_PROGRAM = {
    2, 3, 50, 15, 2, 22, 1, 4, 30, 0, 5, 32, 0, 0, 14, 2,
    0, 10, 1, 0, 12, 1, 6, 36, 34, 1, 1, 1, 0, 8, 4, 2,
    26, 12, 0, 20, 12, 0, 18, 8, 2, 24, 4, 1, 6, 3, 28, 0,
    16, 8, 2, 0, 6, 4, 1, 4
  };
  /**
   * Encrypts, in place, the (encrypted) fields of the Node buffer that starts at
   * _bb.position(), with field-encryption format 3 (key: 32 bytes; recordIndex:
   * an unsigned 32-bit value, unique per buffer under the key). Throws
   * IllegalArgumentException, before any byte changes, for a bad key or a
   * malformed buffer.
   */
  public static void encryptBuffer(ByteBuffer _bb, byte[] key, int recordIndex) {
    FlatbuffersEncryption.cryptBuffer(_bb, key, recordIndex, FLATBUFFERS_ENCRYPTION_PROGRAM);
  }
  /**
   * Decrypts, in place, the (encrypted) fields of the Node buffer that starts at
   * _bb.position(), with field-encryption format 3 (key: 32 bytes; recordIndex:
   * an unsigned 32-bit value, unique per buffer under the key). Throws
   * IllegalArgumentException, before any byte changes, for a bad key or a
   * malformed buffer.
   */
  public static void decryptBuffer(ByteBuffer _bb, byte[] key, int recordIndex) {
    FlatbuffersEncryption.cryptBuffer(_bb, key, recordIndex, FLATBUFFERS_ENCRYPTION_PROGRAM);
  }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String secret() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer secretAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer secretInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public long pin() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public boolean flag() { int o = __offset(10); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public byte level() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) : 1; }
  public short count() { int o = __offset(14); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public long total() { int o = __offset(16); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public double ratio() { int o = __offset(18); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public EncryptionV3.Vec3 position() { return position(new EncryptionV3.Vec3()); }
  public EncryptionV3.Vec3 position(EncryptionV3.Vec3 obj) { int o = __offset(20); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public int bytes(int j) { int o = __offset(22); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int bytesLength() { int o = __offset(22); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector bytesVector() { return bytesVector(new ByteVector()); }
  public ByteVector bytesVector(ByteVector obj) { int o = __offset(22); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer bytesAsByteBuffer() { return __vector_as_bytebuffer(22, 1); }
  public ByteBuffer bytesInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 22, 1); }
  public float readings(int j) { int o = __offset(24); return o != 0 ? bb.getFloat(__vector(o) + j * 4) : 0; }
  public int readingsLength() { int o = __offset(24); return o != 0 ? __vector_len(o) : 0; }
  public FloatVector readingsVector() { return readingsVector(new FloatVector()); }
  public FloatVector readingsVector(FloatVector obj) { int o = __offset(24); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer readingsAsByteBuffer() { return __vector_as_bytebuffer(24, 4); }
  public ByteBuffer readingsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 24, 4); }
  public EncryptionV3.Vec3 points(int j) { return points(new EncryptionV3.Vec3(), j); }
  public EncryptionV3.Vec3 points(EncryptionV3.Vec3 obj, int j) { int o = __offset(26); return o != 0 ? obj.__assign(__vector(o) + j * 12, bb) : null; }
  public int pointsLength() { int o = __offset(26); return o != 0 ? __vector_len(o) : 0; }
  public EncryptionV3.Vec3.Vector pointsVector() { return pointsVector(new EncryptionV3.Vec3.Vector()); }
  public EncryptionV3.Vec3.Vector pointsVector(EncryptionV3.Vec3.Vector obj) { int o = __offset(26); return o != 0 ? obj.__assign(__vector(o), 12, bb) : null; }
  public String tags(int j) { int o = __offset(28); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int tagsLength() { int o = __offset(28); return o != 0 ? __vector_len(o) : 0; }
  public StringVector tagsVector() { return tagsVector(new StringVector()); }
  public StringVector tagsVector(StringVector obj) { int o = __offset(28); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public EncryptionV3.Node child() { return child(new EncryptionV3.Node()); }
  public EncryptionV3.Node child(EncryptionV3.Node obj) { int o = __offset(30); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public EncryptionV3.Node children(int j) { return children(new EncryptionV3.Node(), j); }
  public EncryptionV3.Node children(EncryptionV3.Node obj, int j) { int o = __offset(32); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int childrenLength() { int o = __offset(32); return o != 0 ? __vector_len(o) : 0; }
  public EncryptionV3.Node.Vector childrenVector() { return childrenVector(new EncryptionV3.Node.Vector()); }
  public EncryptionV3.Node.Vector childrenVector(EncryptionV3.Node.Vector obj) { int o = __offset(32); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public byte payloadType() { int o = __offset(34); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public com.google.flatbuffers.Table payload(com.google.flatbuffers.Table obj) { int o = __offset(36); return o != 0 ? __union(obj, o + bb_pos) : null; }
  public long plain() { int o = __offset(38); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static void startNode(FlatBufferBuilder builder) { builder.startTable(18); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addSecret(FlatBufferBuilder builder, int secretOffset) { builder.addOffset(1, secretOffset, 0); }
  public static void addPin(FlatBufferBuilder builder, long pin) { builder.addInt(2, (int) pin, (int) 0L); }
  public static void addFlag(FlatBufferBuilder builder, boolean flag) { builder.addBoolean(3, flag, false); }
  public static void addLevel(FlatBufferBuilder builder, byte level) { builder.addByte(4, level, 1); }
  public static void addCount(FlatBufferBuilder builder, short count) { builder.addShort(5, count, 0); }
  public static void addTotal(FlatBufferBuilder builder, long total) { builder.addLong(6, total, 0L); }
  public static void addRatio(FlatBufferBuilder builder, double ratio) { builder.addDouble(7, ratio, 0.0); }
  public static void addPosition(FlatBufferBuilder builder, int positionOffset) { builder.addStruct(8, positionOffset, 0); }
  public static void addBytes(FlatBufferBuilder builder, int bytesOffset) { builder.addOffset(9, bytesOffset, 0); }
  public static int createBytesVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createBytesVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startBytesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addReadings(FlatBufferBuilder builder, int readingsOffset) { builder.addOffset(10, readingsOffset, 0); }
  public static int createReadingsVector(FlatBufferBuilder builder, float[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addFloat(data[i]); return builder.endVector(); }
  public static void startReadingsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addPoints(FlatBufferBuilder builder, int pointsOffset) { builder.addOffset(11, pointsOffset, 0); }
  public static void startPointsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(12, numElems, 4); }
  public static void addTags(FlatBufferBuilder builder, int tagsOffset) { builder.addOffset(12, tagsOffset, 0); }
  public static int createTagsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTagsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addChild(FlatBufferBuilder builder, int childOffset) { builder.addOffset(13, childOffset, 0); }
  public static void addChildren(FlatBufferBuilder builder, int childrenOffset) { builder.addOffset(14, childrenOffset, 0); }
  public static int createChildrenVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startChildrenVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addPayloadType(FlatBufferBuilder builder, byte payloadType) { builder.addByte(15, payloadType, 0); }
  public static void addPayload(FlatBufferBuilder builder, int payloadOffset) { builder.addOffset(16, payloadOffset, 0); }
  public static void addPlain(FlatBufferBuilder builder, long plain) { builder.addInt(17, (int) plain, (int) 0L); }
  public static int endNode(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishNodeBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedNodeBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Node get(int j) { return get(new Node(), j); }
    public Node get(Node obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

