// automatically generated by the FlatBuffers compiler, do not modify

package EncryptionV3

@Suppress("unused")
class Payload private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val Leaf: UByte = 1u
    }
}
