// automatically generated by the FlatBuffers compiler, do not modify

package EncryptionTest

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Coordinates : Struct() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Coordinates {
        __init(_i, _bb)
        return this
    }
    val lat : Double get() = bb.getDouble(bb_pos + 0)
    val lon : Double get() = bb.getDouble(bb_pos + 8)
    companion object {
        fun createCoordinates(builder: FlatBufferBuilder, lat: Double, lon: Double) : Int {
            builder.prep(8, 16)
            builder.putDouble(lon)
            builder.putDouble(lat)
            return builder.offset()
        }
    }
}
