// automatically generated by the FlatBuffers compiler, do not modify

package EncryptionTest

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class PublicData : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : PublicData {
        __init(_i, _bb)
        return this
    }
    val id : ULong
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val label : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val labelAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(6, 1)
    fun labelInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 6, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_12_19()
        fun getRootAsPublicData(_bb: ByteBuffer): PublicData = getRootAsPublicData(_bb, PublicData())
        fun getRootAsPublicData(_bb: ByteBuffer, obj: PublicData): PublicData {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createPublicData(builder: FlatBufferBuilder, id: ULong, labelOffset: Int) : Int {
            builder.startTable(2)
            addId(builder, id)
            addLabel(builder, labelOffset)
            return endPublicData(builder)
        }
        fun startPublicData(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addId(builder: FlatBufferBuilder, id: ULong) = builder.addLong(0, id.toLong(), 0)
        fun addLabel(builder: FlatBufferBuilder, label: Int) = builder.addOffset(1, label, 0)
        fun endPublicData(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
