// automatically generated by the FlatBuffers compiler, do not modify

package EncryptionTest

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ScalarTest : Table() {

    /** Encryption context for decrypting encrypted fields */
    var encryptionCtx: ByteArray? = null

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __init(_i: Int, _bb: ByteBuffer, _encryptionCtx: ByteArray?)  {
        __reset(_i, _bb)
        encryptionCtx = _encryptionCtx
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ScalarTest {
        __init(_i, _bb)
        return this
    }
    fun __assign(_i: Int, _bb: ByteBuffer, _encryptionCtx: ByteArray?) : ScalarTest {
        __init(_i, _bb, _encryptionCtx)
        return this
    }
    val encryptedBool : Boolean
        get() {
            val o = __offset(4)
            return if(o != 0) {
                val rawValue = 0.toByte() != bb.get(o + bb_pos)
                FlatbuffersEncryption.decryptScalar(rawValue, this.encryptionCtx, 4)
            } else false
        }
    val encryptedByte : Byte
        get() {
            val o = __offset(6)
            return if(o != 0) {
                val rawValue = bb.get(o + bb_pos)
                FlatbuffersEncryption.decryptScalar(rawValue, this.encryptionCtx, 6)
            } else 0
        }
    val encryptedUbyte : UByte
        get() {
            val o = __offset(8)
            return if(o != 0) {
                val rawValue = bb.get(o + bb_pos).toUByte()
                FlatbuffersEncryption.decryptScalar(rawValue, this.encryptionCtx, 8)
            } else 0u
        }
    val encryptedShort : Short
        get() {
            val o = __offset(10)
            return if(o != 0) {
                val rawValue = bb.getShort(o + bb_pos)
                FlatbuffersEncryption.decryptScalar(rawValue, this.encryptionCtx, 10)
            } else 0
        }
    val encryptedUshort : UShort
        get() {
            val o = __offset(12)
            return if(o != 0) {
                val rawValue = bb.getShort(o + bb_pos).toUShort()
                FlatbuffersEncryption.decryptScalar(rawValue, this.encryptionCtx, 12)
            } else 0u
        }
    val encryptedInt : Int
        get() {
            val o = __offset(14)
            return if(o != 0) {
                val rawValue = bb.getInt(o + bb_pos)
                FlatbuffersEncryption.decryptScalar(rawValue, this.encryptionCtx, 14)
            } else 0
        }
    val encryptedUint : UInt
        get() {
            val o = __offset(16)
            return if(o != 0) {
                val rawValue = bb.getInt(o + bb_pos).toUInt()
                FlatbuffersEncryption.decryptScalar(rawValue, this.encryptionCtx, 16)
            } else 0u
        }
    val encryptedLong : Long
        get() {
            val o = __offset(18)
            return if(o != 0) {
                val rawValue = bb.getLong(o + bb_pos)
                FlatbuffersEncryption.decryptScalar(rawValue, this.encryptionCtx, 18)
            } else 0L
        }
    val encryptedUlong : ULong
        get() {
            val o = __offset(20)
            return if(o != 0) {
                val rawValue = bb.getLong(o + bb_pos).toULong()
                FlatbuffersEncryption.decryptScalar(rawValue, this.encryptionCtx, 20)
            } else 0UL
        }
    val encryptedFloat : Float
        get() {
            val o = __offset(22)
            return if(o != 0) {
                val rawValue = bb.getFloat(o + bb_pos)
                FlatbuffersEncryption.decryptScalar(rawValue, this.encryptionCtx, 22)
            } else 0.0f
        }
    val encryptedDouble : Double
        get() {
            val o = __offset(24)
            return if(o != 0) {
                val rawValue = bb.getDouble(o + bb_pos)
                FlatbuffersEncryption.decryptScalar(rawValue, this.encryptionCtx, 24)
            } else 0.0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_12_19()
        fun getRootAsScalarTest(_bb: ByteBuffer): ScalarTest = getRootAsScalarTest(_bb, ScalarTest())
        fun getRootAsScalarTest(_bb: ByteBuffer, obj: ScalarTest): ScalarTest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun getRootAsScalarTest(_bb: ByteBuffer, _encryptionCtx: ByteArray?): ScalarTest = getRootAsScalarTest(_bb, ScalarTest(), _encryptionCtx)
        fun getRootAsScalarTest(_bb: ByteBuffer, obj: ScalarTest, _encryptionCtx: ByteArray?): ScalarTest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb, _encryptionCtx))
        }
        fun createScalarTest(builder: FlatBufferBuilder, encryptedBool: Boolean, encryptedByte: Byte, encryptedUbyte: UByte, encryptedShort: Short, encryptedUshort: UShort, encryptedInt: Int, encryptedUint: UInt, encryptedLong: Long, encryptedUlong: ULong, encryptedFloat: Float, encryptedDouble: Double) : Int {
            builder.startTable(11)
            addEncryptedDouble(builder, encryptedDouble)
            addEncryptedUlong(builder, encryptedUlong)
            addEncryptedLong(builder, encryptedLong)
            addEncryptedFloat(builder, encryptedFloat)
            addEncryptedUint(builder, encryptedUint)
            addEncryptedInt(builder, encryptedInt)
            addEncryptedUshort(builder, encryptedUshort)
            addEncryptedShort(builder, encryptedShort)
            addEncryptedUbyte(builder, encryptedUbyte)
            addEncryptedByte(builder, encryptedByte)
            addEncryptedBool(builder, encryptedBool)
            return endScalarTest(builder)
        }
        fun startScalarTest(builder: FlatBufferBuilder) = builder.startTable(11)
        fun addEncryptedBool(builder: FlatBufferBuilder, encryptedBool: Boolean) = builder.addBoolean(0, encryptedBool, false)
        fun addEncryptedByte(builder: FlatBufferBuilder, encryptedByte: Byte) = builder.addByte(1, encryptedByte, 0)
        fun addEncryptedUbyte(builder: FlatBufferBuilder, encryptedUbyte: UByte) = builder.addByte(2, encryptedUbyte.toByte(), 0)
        fun addEncryptedShort(builder: FlatBufferBuilder, encryptedShort: Short) = builder.addShort(3, encryptedShort, 0)
        fun addEncryptedUshort(builder: FlatBufferBuilder, encryptedUshort: UShort) = builder.addShort(4, encryptedUshort.toShort(), 0)
        fun addEncryptedInt(builder: FlatBufferBuilder, encryptedInt: Int) = builder.addInt(5, encryptedInt, 0)
        fun addEncryptedUint(builder: FlatBufferBuilder, encryptedUint: UInt) = builder.addInt(6, encryptedUint.toInt(), 0)
        fun addEncryptedLong(builder: FlatBufferBuilder, encryptedLong: Long) = builder.addLong(7, encryptedLong, 0L)
        fun addEncryptedUlong(builder: FlatBufferBuilder, encryptedUlong: ULong) = builder.addLong(8, encryptedUlong.toLong(), 0)
        fun addEncryptedFloat(builder: FlatBufferBuilder, encryptedFloat: Float) = builder.addFloat(9, encryptedFloat, 0.0)
        fun addEncryptedDouble(builder: FlatBufferBuilder, encryptedDouble: Double) = builder.addDouble(10, encryptedDouble, 0.0)
        fun endScalarTest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
