// automatically generated by the FlatBuffers compiler, do not modify

package EncryptionTest

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class SensorReading : Table() {

    /** Encryption context for decrypting encrypted fields */
    var encryptionCtx: ByteArray? = null

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __init(_i: Int, _bb: ByteBuffer, _encryptionCtx: ByteArray?)  {
        __reset(_i, _bb)
        encryptionCtx = _encryptionCtx
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SensorReading {
        __init(_i, _bb)
        return this
    }
    fun __assign(_i: Int, _bb: ByteBuffer, _encryptionCtx: ByteArray?) : SensorReading {
        __init(_i, _bb, _encryptionCtx)
        return this
    }
    val deviceId : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val deviceIdAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(4, 1)
    fun deviceIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 4, 1)
    val timestamp : ULong
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val publicData : EncryptionTest.PublicData? get() = publicData(EncryptionTest.PublicData())
    fun publicData(obj: EncryptionTest.PublicData) : EncryptionTest.PublicData? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val location : EncryptionTest.Coordinates? get() = location(EncryptionTest.Coordinates())
    fun location(obj: EncryptionTest.Coordinates) : EncryptionTest.Coordinates? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val temperature : Float
        get() {
            val o = __offset(12)
            return if(o != 0) {
                val rawValue = bb.getFloat(o + bb_pos)
                FlatbuffersEncryption.decryptScalar(rawValue, this.encryptionCtx, 12)
            } else 0.0f
        }
    fun rawData(j: Int) : UByte {
        val o = __offset(14)
        return if (o != 0) {
            bb.get(__vector(o) + j * 1).toUByte()
        } else {
            0u
        }
    }
    val rawDataLength : Int
        get() {
            val o = __offset(14); return if (o != 0) __vector_len(o) else 0
        }
    val rawDataAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(14, 1)
    fun rawDataInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 14, 1)
    val secretMessage : String?
        get() {
            val o = __offset(16)
            return if (o != 0) {
                FlatbuffersEncryption.decryptString(bb, o + bb_pos, this.encryptionCtx, 16)
            } else {
                null
            }
        }
    val secretMessageAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(16, 1)
    fun secretMessageInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 16, 1)
    fun readings(j: Int) : Float {
        val o = __offset(18)
        return if (o != 0) {
            bb.getFloat(__vector(o) + j * 4)
        } else {
            0.0f
        }
    }
    val readingsLength : Int
        get() {
            val o = __offset(18); return if (o != 0) __vector_len(o) else 0
        }
    val readingsAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(18, 4)
    fun readingsInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 18, 4)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_12_19()
        fun getRootAsSensorReading(_bb: ByteBuffer): SensorReading = getRootAsSensorReading(_bb, SensorReading())
        fun getRootAsSensorReading(_bb: ByteBuffer, obj: SensorReading): SensorReading {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun getRootAsSensorReading(_bb: ByteBuffer, _encryptionCtx: ByteArray?): SensorReading = getRootAsSensorReading(_bb, SensorReading(), _encryptionCtx)
        fun getRootAsSensorReading(_bb: ByteBuffer, obj: SensorReading, _encryptionCtx: ByteArray?): SensorReading {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb, _encryptionCtx))
        }
        fun startSensorReading(builder: FlatBufferBuilder) = builder.startTable(8)
        fun addDeviceId(builder: FlatBufferBuilder, deviceId: Int) = builder.addOffset(0, deviceId, 0)
        fun addTimestamp(builder: FlatBufferBuilder, timestamp: ULong) = builder.addLong(1, timestamp.toLong(), 0)
        fun addPublicData(builder: FlatBufferBuilder, publicData: Int) = builder.addOffset(2, publicData, 0)
        fun addLocation(builder: FlatBufferBuilder, location: Int) = builder.addStruct(3, location, 0)
        fun addTemperature(builder: FlatBufferBuilder, temperature: Float) = builder.addFloat(4, temperature, 0.0)
        fun addRawData(builder: FlatBufferBuilder, rawData: Int) = builder.addOffset(5, rawData, 0)
        @kotlin.ExperimentalUnsignedTypes
        fun createRawDataVector(builder: FlatBufferBuilder, data: UByteArray) : Int {
            builder.startVector(1, data.size, 1)
            for (i in data.size - 1 downTo 0) {
                builder.addByte(data[i].toByte())
            }
            return builder.endVector()
        }
        fun startRawDataVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(1, numElems, 1)
        fun addSecretMessage(builder: FlatBufferBuilder, secretMessage: Int) = builder.addOffset(6, secretMessage, 0)
        fun addReadings(builder: FlatBufferBuilder, readings: Int) = builder.addOffset(7, readings, 0)
        fun createReadingsVector(builder: FlatBufferBuilder, data: FloatArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addFloat(data[i])
            }
            return builder.endVector()
        }
        fun startReadingsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endSensorReading(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishSensorReadingBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset)
        fun finishSizePrefixedSensorReadingBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset)
    }
}
