// automatically generated by the FlatBuffers compiler, do not modify

package EncryptionTest

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class UserRecord : Table() {

    /** Encryption context for decrypting encrypted fields */
    var encryptionCtx: ByteArray? = null

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __init(_i: Int, _bb: ByteBuffer, _encryptionCtx: ByteArray?)  {
        __reset(_i, _bb)
        encryptionCtx = _encryptionCtx
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : UserRecord {
        __init(_i, _bb)
        return this
    }
    fun __assign(_i: Int, _bb: ByteBuffer, _encryptionCtx: ByteArray?) : UserRecord {
        __init(_i, _bb, _encryptionCtx)
        return this
    }
    val userId : ULong
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val username : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val usernameAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(6, 1)
    fun usernameInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 6, 1)
    val passwordHash : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                FlatbuffersEncryption.decryptString(bb, o + bb_pos, this.encryptionCtx, 8)
            } else {
                null
            }
        }
    val passwordHashAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(8, 1)
    fun passwordHashInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 8, 1)
    fun privateKey(j: Int) : UByte {
        val o = __offset(10)
        return if (o != 0) {
            bb.get(__vector(o) + j * 1).toUByte()
        } else {
            0u
        }
    }
    val privateKeyLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    val privateKeyAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(10, 1)
    fun privateKeyInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 10, 1)
    val ssn : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                FlatbuffersEncryption.decryptString(bb, o + bb_pos, this.encryptionCtx, 12)
            } else {
                null
            }
        }
    val ssnAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(12, 1)
    fun ssnInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 12, 1)
    val balance : Double
        get() {
            val o = __offset(14)
            return if(o != 0) {
                val rawValue = bb.getDouble(o + bb_pos)
                FlatbuffersEncryption.decryptScalar(rawValue, this.encryptionCtx, 14)
            } else 0.0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_12_19()
        fun getRootAsUserRecord(_bb: ByteBuffer): UserRecord = getRootAsUserRecord(_bb, UserRecord())
        fun getRootAsUserRecord(_bb: ByteBuffer, obj: UserRecord): UserRecord {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun getRootAsUserRecord(_bb: ByteBuffer, _encryptionCtx: ByteArray?): UserRecord = getRootAsUserRecord(_bb, UserRecord(), _encryptionCtx)
        fun getRootAsUserRecord(_bb: ByteBuffer, obj: UserRecord, _encryptionCtx: ByteArray?): UserRecord {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb, _encryptionCtx))
        }
        fun createUserRecord(builder: FlatBufferBuilder, userId: ULong, usernameOffset: Int, passwordHashOffset: Int, privateKeyOffset: Int, ssnOffset: Int, balance: Double) : Int {
            builder.startTable(6)
            addBalance(builder, balance)
            addUserId(builder, userId)
            addSsn(builder, ssnOffset)
            addPrivateKey(builder, privateKeyOffset)
            addPasswordHash(builder, passwordHashOffset)
            addUsername(builder, usernameOffset)
            return endUserRecord(builder)
        }
        fun startUserRecord(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addUserId(builder: FlatBufferBuilder, userId: ULong) = builder.addLong(0, userId.toLong(), 0)
        fun addUsername(builder: FlatBufferBuilder, username: Int) = builder.addOffset(1, username, 0)
        fun addPasswordHash(builder: FlatBufferBuilder, passwordHash: Int) = builder.addOffset(2, passwordHash, 0)
        fun addPrivateKey(builder: FlatBufferBuilder, privateKey: Int) = builder.addOffset(3, privateKey, 0)
        @kotlin.ExperimentalUnsignedTypes
        fun createPrivateKeyVector(builder: FlatBufferBuilder, data: UByteArray) : Int {
            builder.startVector(1, data.size, 1)
            for (i in data.size - 1 downTo 0) {
                builder.addByte(data[i].toByte())
            }
            return builder.endVector()
        }
        fun startPrivateKeyVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(1, numElems, 1)
        fun addSsn(builder: FlatBufferBuilder, ssn: Int) = builder.addOffset(4, ssn, 0)
        fun addBalance(builder: FlatBufferBuilder, balance: Double) = builder.addDouble(5, balance, 0.0)
        fun endUserRecord(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
