import * as flatbuffers from 'flatbuffers';
import { OptionalByte } from '../optional-scalars/optional-byte';
export declare class ScalarStuff {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): ScalarStuff;
    static getRootAsScalarStuff(bb: flatbuffers.ByteBuffer, obj?: ScalarStuff): ScalarStuff;
    static getSizePrefixedRootAsScalarStuff(bb: flatbuffers.ByteBuffer, obj?: ScalarStuff): ScalarStuff;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    just_i8(): number;
    maybe_i8(): number | null;
    default_i8(): number;
    just_u8(): number;
    maybe_u8(): number | null;
    default_u8(): number;
    just_i16(): number;
    maybe_i16(): number | null;
    default_i16(): number;
    just_u16(): number;
    maybe_u16(): number | null;
    default_u16(): number;
    just_i32(): number;
    maybe_i32(): number | null;
    default_i32(): number;
    just_u32(): number;
    maybe_u32(): number | null;
    default_u32(): number;
    just_i64(): bigint;
    maybe_i64(): bigint | null;
    default_i64(): bigint;
    just_u64(): bigint;
    maybe_u64(): bigint | null;
    default_u64(): bigint;
    just_f32(): number;
    maybe_f32(): number | null;
    default_f32(): number;
    just_f64(): number;
    maybe_f64(): number | null;
    default_f64(): number;
    just_bool(): boolean;
    maybe_bool(): boolean | null;
    default_bool(): boolean;
    just_enum(): OptionalByte;
    maybe_enum(): OptionalByte | null;
    default_enum(): OptionalByte;
    static getFullyQualifiedName(): string;
    static startScalarStuff(builder: flatbuffers.Builder): void;
    static add_just_i8(builder: flatbuffers.Builder, justI8: number): void;
    static add_maybe_i8(builder: flatbuffers.Builder, maybeI8: number): void;
    static add_default_i8(builder: flatbuffers.Builder, defaultI8: number): void;
    static add_just_u8(builder: flatbuffers.Builder, justU8: number): void;
    static add_maybe_u8(builder: flatbuffers.Builder, maybeU8: number): void;
    static add_default_u8(builder: flatbuffers.Builder, defaultU8: number): void;
    static add_just_i16(builder: flatbuffers.Builder, justI16: number): void;
    static add_maybe_i16(builder: flatbuffers.Builder, maybeI16: number): void;
    static add_default_i16(builder: flatbuffers.Builder, defaultI16: number): void;
    static add_just_u16(builder: flatbuffers.Builder, justU16: number): void;
    static add_maybe_u16(builder: flatbuffers.Builder, maybeU16: number): void;
    static add_default_u16(builder: flatbuffers.Builder, defaultU16: number): void;
    static add_just_i32(builder: flatbuffers.Builder, justI32: number): void;
    static add_maybe_i32(builder: flatbuffers.Builder, maybeI32: number): void;
    static add_default_i32(builder: flatbuffers.Builder, defaultI32: number): void;
    static add_just_u32(builder: flatbuffers.Builder, justU32: number): void;
    static add_maybe_u32(builder: flatbuffers.Builder, maybeU32: number): void;
    static add_default_u32(builder: flatbuffers.Builder, defaultU32: number): void;
    static add_just_i64(builder: flatbuffers.Builder, justI64: bigint): void;
    static add_maybe_i64(builder: flatbuffers.Builder, maybeI64: bigint): void;
    static add_default_i64(builder: flatbuffers.Builder, defaultI64: bigint): void;
    static add_just_u64(builder: flatbuffers.Builder, justU64: bigint): void;
    static add_maybe_u64(builder: flatbuffers.Builder, maybeU64: bigint): void;
    static add_default_u64(builder: flatbuffers.Builder, defaultU64: bigint): void;
    static add_just_f32(builder: flatbuffers.Builder, justF32: number): void;
    static add_maybe_f32(builder: flatbuffers.Builder, maybeF32: number): void;
    static add_default_f32(builder: flatbuffers.Builder, defaultF32: number): void;
    static add_just_f64(builder: flatbuffers.Builder, justF64: number): void;
    static add_maybe_f64(builder: flatbuffers.Builder, maybeF64: number): void;
    static add_default_f64(builder: flatbuffers.Builder, defaultF64: number): void;
    static add_just_bool(builder: flatbuffers.Builder, justBool: boolean): void;
    static add_maybe_bool(builder: flatbuffers.Builder, maybeBool: boolean): void;
    static add_default_bool(builder: flatbuffers.Builder, defaultBool: boolean): void;
    static add_just_enum(builder: flatbuffers.Builder, justEnum: OptionalByte): void;
    static add_maybe_enum(builder: flatbuffers.Builder, maybeEnum: OptionalByte): void;
    static add_default_enum(builder: flatbuffers.Builder, defaultEnum: OptionalByte): void;
    static endScalarStuff(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishScalarStuffBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedScalarStuffBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createScalarStuff(builder: flatbuffers.Builder, justI8: number, maybeI8: number | null, defaultI8: number, justU8: number, maybeU8: number | null, defaultU8: number, justI16: number, maybeI16: number | null, defaultI16: number, justU16: number, maybeU16: number | null, defaultU16: number, justI32: number, maybeI32: number | null, defaultI32: number, justU32: number, maybeU32: number | null, defaultU32: number, justI64: bigint, maybeI64: bigint | null, defaultI64: bigint, justU64: bigint, maybeU64: bigint | null, defaultU64: bigint, justF32: number, maybeF32: number | null, defaultF32: number, justF64: number, maybeF64: number | null, defaultF64: number, justBool: boolean, maybeBool: boolean | null, defaultBool: boolean, justEnum: OptionalByte, maybeEnum: OptionalByte | null, defaultEnum: OptionalByte): flatbuffers.Offset;
}
