// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { FlatbuffersEncryption } from './flatbuffers-encryption.js';


export class ScalarTest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  encryptionCtx: Uint8Array|null = null;
  __init(i:number, bb:flatbuffers.ByteBuffer, encryptionCtx?: Uint8Array):ScalarTest {
  this.bb_pos = i;
  this.bb = bb;
  this.encryptionCtx = encryptionCtx || null;
  return this;
}

static getRootAsScalarTest(bb:flatbuffers.ByteBuffer, obj?:ScalarTest, encryptionCtx?: Uint8Array):ScalarTest {
  return (obj || new ScalarTest()).__init(bb.readInt32(bb.position()) + bb.position(), bb, encryptionCtx);
}

static getSizePrefixedRootAsScalarTest(bb:flatbuffers.ByteBuffer, obj?:ScalarTest, encryptionCtx?: Uint8Array):ScalarTest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ScalarTest()).__init(bb.readInt32(bb.position()) + bb.position(), bb, encryptionCtx);
}

encryptedBool():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? FlatbuffersEncryption.decryptScalar(!!this.bb!.readInt8(this.bb_pos + offset), this.encryptionCtx, 4) : false;
}

encryptedByte():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? FlatbuffersEncryption.decryptScalar(this.bb!.readInt8(this.bb_pos + offset), this.encryptionCtx, 6) : 0;
}

encryptedUbyte():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? FlatbuffersEncryption.decryptScalar(this.bb!.readUint8(this.bb_pos + offset), this.encryptionCtx, 8) : 0;
}

encryptedShort():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? FlatbuffersEncryption.decryptScalar(this.bb!.readInt16(this.bb_pos + offset), this.encryptionCtx, 10) : 0;
}

encryptedUshort():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? FlatbuffersEncryption.decryptScalar(this.bb!.readUint16(this.bb_pos + offset), this.encryptionCtx, 12) : 0;
}

encryptedInt():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? FlatbuffersEncryption.decryptScalar(this.bb!.readInt32(this.bb_pos + offset), this.encryptionCtx, 14) : 0;
}

encryptedUint():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? FlatbuffersEncryption.decryptScalar(this.bb!.readUint32(this.bb_pos + offset), this.encryptionCtx, 16) : 0;
}

encryptedLong():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? FlatbuffersEncryption.decryptScalar(this.bb!.readInt64(this.bb_pos + offset), this.encryptionCtx, 18) : BigInt('0');
}

encryptedUlong():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? FlatbuffersEncryption.decryptScalar(this.bb!.readUint64(this.bb_pos + offset), this.encryptionCtx, 20) : BigInt('0');
}

encryptedFloat():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? FlatbuffersEncryption.decryptScalar(this.bb!.readFloat32(this.bb_pos + offset), this.encryptionCtx, 22) : 0.0;
}

encryptedDouble():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? FlatbuffersEncryption.decryptScalar(this.bb!.readFloat64(this.bb_pos + offset), this.encryptionCtx, 24) : 0.0;
}

static startScalarTest(builder:flatbuffers.Builder) {
  builder.startObject(11);
}

static addEncryptedBool(builder:flatbuffers.Builder, encryptedBool:boolean) {
  builder.addFieldInt8(0, +encryptedBool, +false);
}

static addEncryptedByte(builder:flatbuffers.Builder, encryptedByte:number) {
  builder.addFieldInt8(1, encryptedByte, 0);
}

static addEncryptedUbyte(builder:flatbuffers.Builder, encryptedUbyte:number) {
  builder.addFieldInt8(2, encryptedUbyte, 0);
}

static addEncryptedShort(builder:flatbuffers.Builder, encryptedShort:number) {
  builder.addFieldInt16(3, encryptedShort, 0);
}

static addEncryptedUshort(builder:flatbuffers.Builder, encryptedUshort:number) {
  builder.addFieldInt16(4, encryptedUshort, 0);
}

static addEncryptedInt(builder:flatbuffers.Builder, encryptedInt:number) {
  builder.addFieldInt32(5, encryptedInt, 0);
}

static addEncryptedUint(builder:flatbuffers.Builder, encryptedUint:number) {
  builder.addFieldInt32(6, encryptedUint, 0);
}

static addEncryptedLong(builder:flatbuffers.Builder, encryptedLong:bigint) {
  builder.addFieldInt64(7, encryptedLong, BigInt('0'));
}

static addEncryptedUlong(builder:flatbuffers.Builder, encryptedUlong:bigint) {
  builder.addFieldInt64(8, encryptedUlong, BigInt('0'));
}

static addEncryptedFloat(builder:flatbuffers.Builder, encryptedFloat:number) {
  builder.addFieldFloat32(9, encryptedFloat, 0.0);
}

static addEncryptedDouble(builder:flatbuffers.Builder, encryptedDouble:number) {
  builder.addFieldFloat64(10, encryptedDouble, 0.0);
}

static endScalarTest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createScalarTest(builder:flatbuffers.Builder, encryptedBool:boolean, encryptedByte:number, encryptedUbyte:number, encryptedShort:number, encryptedUshort:number, encryptedInt:number, encryptedUint:number, encryptedLong:bigint, encryptedUlong:bigint, encryptedFloat:number, encryptedDouble:number):flatbuffers.Offset {
  ScalarTest.startScalarTest(builder);
  ScalarTest.addEncryptedBool(builder, encryptedBool);
  ScalarTest.addEncryptedByte(builder, encryptedByte);
  ScalarTest.addEncryptedUbyte(builder, encryptedUbyte);
  ScalarTest.addEncryptedShort(builder, encryptedShort);
  ScalarTest.addEncryptedUshort(builder, encryptedUshort);
  ScalarTest.addEncryptedInt(builder, encryptedInt);
  ScalarTest.addEncryptedUint(builder, encryptedUint);
  ScalarTest.addEncryptedLong(builder, encryptedLong);
  ScalarTest.addEncryptedUlong(builder, encryptedUlong);
  ScalarTest.addEncryptedFloat(builder, encryptedFloat);
  ScalarTest.addEncryptedDouble(builder, encryptedDouble);
  return ScalarTest.endScalarTest(builder);
}
}
