<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace EncryptionTest;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class PublicData extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return PublicData
     */
    public static function getRootAsPublicData(ByteBuffer $bb)
    {
        $obj = new PublicData();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return PublicData
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return ulong
     */
    public function getId()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->bb->getUlong($o + $this->bb_pos) : 0;
    }

    public function getLabel()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startPublicData(FlatBufferBuilder $builder)
    {
        $builder->StartObject(2);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return PublicData
     */
    public static function createPublicData(FlatBufferBuilder $builder, $id, $label)
    {
        $builder->startObject(2);
        self::addId($builder, $id);
        self::addLabel($builder, $label);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param ulong
     * @return void
     */
    public static function addId(FlatBufferBuilder $builder, $id)
    {
        $builder->addUlongX(0, $id, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addLabel(FlatBufferBuilder $builder, $label)
    {
        $builder->addOffsetX(1, $label, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endPublicData(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
