// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Crypto

import "strconv"

/// Supported elliptic curves for key exchange
type Curve int8

const (
	CurveX25519    Curve = 0
	CurveSecp256k1 Curve = 1
	CurveP256      Curve = 2
)

var EnumNamesCurve = map[Curve]string{
	CurveX25519:    "X25519",
	CurveSecp256k1: "Secp256k1",
	CurveP256:      "P256",
}

var EnumValuesCurve = map[string]Curve{
	"X25519":    CurveX25519,
	"Secp256k1": CurveSecp256k1,
	"P256":      CurveP256,
}

func (v Curve) String() string {
	if s, ok := EnumNamesCurve[v]; ok {
		return s
	}
	return "Curve(" + strconv.FormatInt(int64(v), 10) + ")"
}
