// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Crypto

import "strconv"

/// Symmetric encryption algorithm
type EncryptionAlgorithm int8

const (
	EncryptionAlgorithmAES_256_CTR EncryptionAlgorithm = 0
)

var EnumNamesEncryptionAlgorithm = map[EncryptionAlgorithm]string{
	EncryptionAlgorithmAES_256_CTR: "AES_256_CTR",
}

var EnumValuesEncryptionAlgorithm = map[string]EncryptionAlgorithm{
	"AES_256_CTR": EncryptionAlgorithmAES_256_CTR,
}

func (v EncryptionAlgorithm) String() string {
	if s, ok := EnumNamesEncryptionAlgorithm[v]; ok {
		return s
	}
	return "EncryptionAlgorithm(" + strconv.FormatInt(int64(v), 10) + ")"
}
