// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Crypto

import "strconv"

/// Key exchange algorithm
type KeyExchangeAlgorithm int8

const (
	KeyExchangeAlgorithmECDH KeyExchangeAlgorithm = 0
)

var EnumNamesKeyExchangeAlgorithm = map[KeyExchangeAlgorithm]string{
	KeyExchangeAlgorithmECDH: "ECDH",
}

var EnumValuesKeyExchangeAlgorithm = map[string]KeyExchangeAlgorithm{
	"ECDH": KeyExchangeAlgorithmECDH,
}

func (v KeyExchangeAlgorithm) String() string {
	if s, ok := EnumNamesKeyExchangeAlgorithm[v]; ok {
		return s
	}
	return "KeyExchangeAlgorithm(" + strconv.FormatInt(int64(v), 10) + ")"
}
