// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Crypto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Wrapper for encrypted/unencrypted messages
type SecureMessage struct {
	_tab flatbuffers.Table
}

const SecureMessageIdentifier = "SECM"

func GetRootAsSecureMessage(buf []byte, offset flatbuffers.UOffsetT) *SecureMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SecureMessage{}
	x.Init(buf, n+offset)
	return x
}

func FinishSecureMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(SecureMessageIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func SecureMessageBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, SecureMessageIdentifier)
}

func GetSizePrefixedRootAsSecureMessage(buf []byte, offset flatbuffers.UOffsetT) *SecureMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SecureMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSecureMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(SecureMessageIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedSecureMessageBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, SecureMessageIdentifier)
}

func (rcv *SecureMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SecureMessage) Table() flatbuffers.Table {
	return rcv._tab
}

/// Unique message identifier
func (rcv *SecureMessage) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Unique message identifier
/// Sender identifier
func (rcv *SecureMessage) Sender() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Sender identifier
/// Recipient identifier
func (rcv *SecureMessage) Recipient() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Recipient identifier
/// Message payload (can be encrypted)
func (rcv *SecureMessage) Payload(obj *Payload) *Payload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Payload)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

/// Message payload (can be encrypted)
/// Timestamp
func (rcv *SecureMessage) Timestamp() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

/// Timestamp
func (rcv *SecureMessage) MutateTimestamp(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

/// Signature (optional, for signed messages)
func (rcv *SecureMessage) Signature(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *SecureMessage) SignatureLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SecureMessage) SignatureBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Signature (optional, for signed messages)
func (rcv *SecureMessage) MutateSignature(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func SecureMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func SecureMessageAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func SecureMessageAddSender(builder *flatbuffers.Builder, sender flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(sender), 0)
}
func SecureMessageAddRecipient(builder *flatbuffers.Builder, recipient flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(recipient), 0)
}
func SecureMessageAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(payload), 0)
}
func SecureMessageAddTimestamp(builder *flatbuffers.Builder, timestamp uint64) {
	builder.PrependUint64Slot(4, timestamp, 0)
}
func SecureMessageAddSignature(builder *flatbuffers.Builder, signature flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(signature), 0)
}
func SecureMessageStartSignatureVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func SecureMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
