// automatically generated by the FlatBuffers compiler, do not modify

package E2E.Crypto;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * Public key for key exchange (as a table to support all languages)
 */
@SuppressWarnings("unused")
public final class PublicKey extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_12_23(); }
  public static PublicKey getRootAsPublicKey(ByteBuffer _bb) { return getRootAsPublicKey(_bb, new PublicKey()); }
  public static PublicKey getRootAsPublicKey(ByteBuffer _bb, PublicKey obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PublicKey __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * Key bytes (32 or 33 bytes depending on curve)
   */
  public int data(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int dataLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector dataVector() { return dataVector(new ByteVector()); }
  public ByteVector dataVector(ByteVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer dataAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer dataInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  /**
   * Length of valid key data (32 for X25519/P-256, 33 for secp256k1 compressed)
   */
  public int length() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createPublicKey(FlatBufferBuilder builder,
      int dataOffset,
      int length) {
    builder.startTable(2);
    PublicKey.addData(builder, dataOffset);
    PublicKey.addLength(builder, length);
    return PublicKey.endPublicKey(builder);
  }

  public static void startPublicKey(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addData(FlatBufferBuilder builder, int dataOffset) { builder.addOffset(0, dataOffset, 0); }
  public static int createDataVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createDataVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startDataVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addLength(FlatBufferBuilder builder, int length) { builder.addByte(1, (byte) length, (byte) 0); }
  public static int endPublicKey(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PublicKey get(int j) { return get(new PublicKey(), j); }
    public PublicKey get(PublicKey obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

