// automatically generated by the FlatBuffers compiler, do not modify

package E2E.Crypto;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * Wrapper for encrypted/unencrypted messages
 */
@SuppressWarnings("unused")
public final class SecureMessage extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_12_23(); }
  public static SecureMessage getRootAsSecureMessage(ByteBuffer _bb) { return getRootAsSecureMessage(_bb, new SecureMessage()); }
  public static SecureMessage getRootAsSecureMessage(ByteBuffer _bb, SecureMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public static boolean SecureMessageBufferHasIdentifier(ByteBuffer _bb) { return __has_identifier(_bb, "SECM"); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SecureMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * Unique message identifier
   */
  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  /**
   * Sender identifier
   */
  public String sender() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer senderAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer senderInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  /**
   * Recipient identifier
   */
  public String recipient() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer recipientAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer recipientInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  /**
   * Message payload (can be encrypted)
   */
  public E2E.Crypto.Payload payload() { return payload(new E2E.Crypto.Payload()); }
  public E2E.Crypto.Payload payload(E2E.Crypto.Payload obj) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  /**
   * Timestamp
   */
  public long timestamp() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  /**
   * Signature (optional, for signed messages)
   */
  public int signature(int j) { int o = __offset(14); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int signatureLength() { int o = __offset(14); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector signatureVector() { return signatureVector(new ByteVector()); }
  public ByteVector signatureVector(ByteVector obj) { int o = __offset(14); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer signatureAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer signatureInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }

  public static int createSecureMessage(FlatBufferBuilder builder,
      int idOffset,
      int senderOffset,
      int recipientOffset,
      int payloadOffset,
      long timestamp,
      int signatureOffset) {
    builder.startTable(6);
    SecureMessage.addTimestamp(builder, timestamp);
    SecureMessage.addSignature(builder, signatureOffset);
    SecureMessage.addPayload(builder, payloadOffset);
    SecureMessage.addRecipient(builder, recipientOffset);
    SecureMessage.addSender(builder, senderOffset);
    SecureMessage.addId(builder, idOffset);
    return SecureMessage.endSecureMessage(builder);
  }

  public static void startSecureMessage(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addSender(FlatBufferBuilder builder, int senderOffset) { builder.addOffset(1, senderOffset, 0); }
  public static void addRecipient(FlatBufferBuilder builder, int recipientOffset) { builder.addOffset(2, recipientOffset, 0); }
  public static void addPayload(FlatBufferBuilder builder, int payloadOffset) { builder.addOffset(3, payloadOffset, 0); }
  public static void addTimestamp(FlatBufferBuilder builder, long timestamp) { builder.addLong(4, timestamp, 0L); }
  public static void addSignature(FlatBufferBuilder builder, int signatureOffset) { builder.addOffset(5, signatureOffset, 0); }
  public static int createSignatureVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createSignatureVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startSignatureVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endSecureMessage(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishSecureMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset, "SECM"); }
  public static void finishSizePrefixedSecureMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset, "SECM"); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SecureMessage get(int j) { return get(new SecureMessage(), j); }
    public SecureMessage get(SecureMessage obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

