// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace E2E.Crypto
{

/// Supported elliptic curves for key exchange
public enum Curve : sbyte
{
  X25519 = 0,
  Secp256k1 = 1,
  P256 = 2,
};


}
