// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace E2E.Crypto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

/// A simple payload for testing
public struct Payload : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_12_23(); }
  public static Payload GetRootAsPayload(ByteBuffer _bb) { return GetRootAsPayload(_bb, new Payload()); }
  public static Payload GetRootAsPayload(ByteBuffer _bb, Payload obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Payload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /// Message content
  public string Message { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMessageBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetMessageBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetMessageArray() { return __p.__vector_as_array<byte>(4); }
  /// Numeric value
  public int Value { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  /// Binary data
  public byte Data(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int DataLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDataBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetDataBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetDataArray() { return __p.__vector_as_array<byte>(8); }
  /// Nested messages
  public E2E.Crypto.Payload? Nested(int j) { int o = __p.__offset(10); return o != 0 ? (E2E.Crypto.Payload?)(new E2E.Crypto.Payload()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int NestedLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
  /// Boolean flag
  public bool IsEncrypted { get { int o = __p.__offset(12); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<E2E.Crypto.Payload> CreatePayload(FlatBufferBuilder builder,
      StringOffset messageOffset = default(StringOffset),
      int value = 0,
      VectorOffset dataOffset = default(VectorOffset),
      VectorOffset nestedOffset = default(VectorOffset),
      bool is_encrypted = false) {
    builder.StartTable(5);
    Payload.AddNested(builder, nestedOffset);
    Payload.AddData(builder, dataOffset);
    Payload.AddValue(builder, value);
    Payload.AddMessage(builder, messageOffset);
    Payload.AddIsEncrypted(builder, is_encrypted);
    return Payload.EndPayload(builder);
  }

  public static void StartPayload(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddMessage(FlatBufferBuilder builder, StringOffset messageOffset) { builder.AddOffset(0, messageOffset.Value, 0); }
  public static void AddValue(FlatBufferBuilder builder, int value) { builder.AddInt(1, value, 0); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(2, dataOffset.Value, 0); }
  public static VectorOffset CreateDataVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static void AddNested(FlatBufferBuilder builder, VectorOffset nestedOffset) { builder.AddOffset(3, nestedOffset.Value, 0); }
  public static VectorOffset CreateNestedVector(FlatBufferBuilder builder, Offset<E2E.Crypto.Payload>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateNestedVectorBlock(FlatBufferBuilder builder, Offset<E2E.Crypto.Payload>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateNestedVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<E2E.Crypto.Payload>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateNestedVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<E2E.Crypto.Payload>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartNestedVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddIsEncrypted(FlatBufferBuilder builder, bool isEncrypted) { builder.AddBool(4, isEncrypted, false); }
  public static Offset<E2E.Crypto.Payload> EndPayload(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<E2E.Crypto.Payload>(o);
  }
}


static public class PayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Message*/, false)
      && verifier.VerifyField(tablePos, 6 /*Value*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 8 /*Data*/, 1 /*byte*/, false)
      && verifier.VerifyVectorOfTables(tablePos, 10 /*Nested*/, E2E.Crypto.PayloadVerify.Verify, false)
      && verifier.VerifyField(tablePos, 12 /*IsEncrypted*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
