from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from MyGame.MonsterExtra import MonsterExtra

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MonsterExtra(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MonsterExtra: ...
  @classmethod
  def GetRootAsMonsterExtra(cls, buf: bytes, offset: int) -> MonsterExtra: ...
  @classmethod
  def MonsterExtraBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def d0(self) -> float: ...
  def d1(self) -> float: ...
  def d2(self) -> float: ...
  def d3(self) -> float: ...
  def f0(self) -> float: ...
  def f1(self) -> float: ...
  def f2(self) -> float: ...
  def f3(self) -> float: ...
  def dvec(self, i: int) -> typing.List[float]: ...
  def dvecAsNumpy(self) -> np.ndarray: ...
  def dvecLength(self) -> int: ...
  def dvecIsNone(self) -> bool: ...
  def fvec(self, i: int) -> typing.List[float]: ...
  def fvecAsNumpy(self) -> np.ndarray: ...
  def fvecLength(self) -> int: ...
  def fvecIsNone(self) -> bool: ...
class MonsterExtraT(object):
  d0: float
  d1: float
  d2: float
  d3: float
  f0: float
  f1: float
  f2: float
  f3: float
  dvec: typing.List[float]
  fvec: typing.List[float]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> MonsterExtraT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> MonsterExtraT: ...
  @classmethod
  def InitFromObj(cls, MonsterExtra: MonsterExtra) -> MonsterExtraT: ...
  def _UnPack(self, MonsterExtra: MonsterExtra) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
  def __eq__(self, other: MonsterExtraT) -> bool: ...
def MonsterExtraStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MonsterExtraAddd0(builder: flatbuffers.Builder, d0: float) -> None: ...
def MonsterExtraAddd1(builder: flatbuffers.Builder, d1: float) -> None: ...
def MonsterExtraAddd2(builder: flatbuffers.Builder, d2: float) -> None: ...
def MonsterExtraAddd3(builder: flatbuffers.Builder, d3: float) -> None: ...
def MonsterExtraAddf0(builder: flatbuffers.Builder, f0: float) -> None: ...
def MonsterExtraAddf1(builder: flatbuffers.Builder, f1: float) -> None: ...
def MonsterExtraAddf2(builder: flatbuffers.Builder, f2: float) -> None: ...
def MonsterExtraAddf3(builder: flatbuffers.Builder, f3: float) -> None: ...
def MonsterExtraAdddvec(builder: flatbuffers.Builder, dvec: uoffset) -> None: ...
def MonsterExtraStartdvecVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartdvecVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def MonsterExtraAddfvec(builder: flatbuffers.Builder, fvec: uoffset) -> None: ...
def MonsterExtraStartfvecVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartfvecVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def MonsterExtraEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

