# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MyGame

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class MonsterExtra(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MonsterExtra()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMonsterExtra(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MonsterExtraBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x4E\x45", size_prefixed=size_prefixed)

    # MonsterExtra
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MonsterExtra
    def d0(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.float64Flags, o + self._tab.Pos)
        return float('nan')

    # MonsterExtra
    def d1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.float64Flags, o + self._tab.Pos)
        return float('nan')

    # MonsterExtra
    def d2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.float64Flags, o + self._tab.Pos)
        return float('inf')

    # MonsterExtra
    def d3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.float64Flags, o + self._tab.Pos)
        return float('-inf')

    # MonsterExtra
    def f0(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.float32Flags, o + self._tab.Pos)
        return float('nan')

    # MonsterExtra
    def f1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.float32Flags, o + self._tab.Pos)
        return float('nan')

    # MonsterExtra
    def f2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.float32Flags, o + self._tab.Pos)
        return float('inf')

    # MonsterExtra
    def f3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.float32Flags, o + self._tab.Pos)
        return float('-inf')

    # MonsterExtra
    def dvec(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # MonsterExtra
    def dvecAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.float64Flags, o)
        return 0

    # MonsterExtra
    def dvecLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MonsterExtra
    def dvecIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # MonsterExtra
    def fvec(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # MonsterExtra
    def fvecAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.float32Flags, o)
        return 0

    # MonsterExtra
    def fvecLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MonsterExtra
    def fvecIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

def MonsterExtraStart(builder: flatbuffers.Builder):
    builder.StartObject(11)

def Start(builder: flatbuffers.Builder):
    MonsterExtraStart(builder)

def MonsterExtraAddd0(builder: flatbuffers.Builder, d0: float):
    builder.Prependfloat64Slot(0, d0, float('nan'))

def Addd0(builder: flatbuffers.Builder, d0: float):
    MonsterExtraAddd0(builder, d0)

def MonsterExtraAddd1(builder: flatbuffers.Builder, d1: float):
    builder.Prependfloat64Slot(1, d1, float('nan'))

def Addd1(builder: flatbuffers.Builder, d1: float):
    MonsterExtraAddd1(builder, d1)

def MonsterExtraAddd2(builder: flatbuffers.Builder, d2: float):
    builder.Prependfloat64Slot(2, d2, float('inf'))

def Addd2(builder: flatbuffers.Builder, d2: float):
    MonsterExtraAddd2(builder, d2)

def MonsterExtraAddd3(builder: flatbuffers.Builder, d3: float):
    builder.Prependfloat64Slot(3, d3, float('-inf'))

def Addd3(builder: flatbuffers.Builder, d3: float):
    MonsterExtraAddd3(builder, d3)

def MonsterExtraAddf0(builder: flatbuffers.Builder, f0: float):
    builder.Prependfloat32Slot(4, f0, float('nan'))

def Addf0(builder: flatbuffers.Builder, f0: float):
    MonsterExtraAddf0(builder, f0)

def MonsterExtraAddf1(builder: flatbuffers.Builder, f1: float):
    builder.Prependfloat32Slot(5, f1, float('nan'))

def Addf1(builder: flatbuffers.Builder, f1: float):
    MonsterExtraAddf1(builder, f1)

def MonsterExtraAddf2(builder: flatbuffers.Builder, f2: float):
    builder.Prependfloat32Slot(6, f2, float('inf'))

def Addf2(builder: flatbuffers.Builder, f2: float):
    MonsterExtraAddf2(builder, f2)

def MonsterExtraAddf3(builder: flatbuffers.Builder, f3: float):
    builder.Prependfloat32Slot(7, f3, float('-inf'))

def Addf3(builder: flatbuffers.Builder, f3: float):
    MonsterExtraAddf3(builder, f3)

def MonsterExtraAdddvec(builder: flatbuffers.Builder, dvec: int):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(dvec), 0)

def Adddvec(builder: flatbuffers.Builder, dvec: int):
    MonsterExtraAdddvec(builder, dvec)

def MonsterExtraStartdvecVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartdvecVector(builder, numElems: int) -> int:
    return MonsterExtraStartdvecVector(builder, numElems)

def MonsterExtraAddfvec(builder: flatbuffers.Builder, fvec: int):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(fvec), 0)

def Addfvec(builder: flatbuffers.Builder, fvec: int):
    MonsterExtraAddfvec(builder, fvec)

def MonsterExtraStartfvecVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartfvecVector(builder, numElems: int) -> int:
    return MonsterExtraStartfvecVector(builder, numElems)

def MonsterExtraEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return MonsterExtraEnd(builder)

try:
    from typing import List
except:
    pass

class MonsterExtraT(object):

    # MonsterExtraT
    def __init__(self):
        self.d0 = float('nan')  # type: float
        self.d1 = float('nan')  # type: float
        self.d2 = float('inf')  # type: float
        self.d3 = float('-inf')  # type: float
        self.f0 = float('nan')  # type: float
        self.f1 = float('nan')  # type: float
        self.f2 = float('inf')  # type: float
        self.f3 = float('-inf')  # type: float
        self.dvec = None  # type: List[float]
        self.fvec = None  # type: List[float]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        MonsterExtra = MonsterExtra()
        MonsterExtra.Init(buf, pos)
        return cls.InitFromObj(MonsterExtra)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, MonsterExtra):
        x = MonsterExtraT()
        x._UnPack(MonsterExtra)
        return x

    def __eq__(self, other):
        return type(self) == type(other) and \
            self.d0 == other.d0 and \
            self.d1 == other.d1 and \
            self.d2 == other.d2 and \
            self.d3 == other.d3 and \
            self.f0 == other.f0 and \
            self.f1 == other.f1 and \
            self.f2 == other.f2 and \
            self.f3 == other.f3 and \
            self.dvec == other.dvec and \
            self.fvec == other.fvec

    # MonsterExtraT
    def _UnPack(self, MonsterExtra):
        if MonsterExtra is None:
            return
        self.d0 = MonsterExtra.d0()
        self.d1 = MonsterExtra.d1()
        self.d2 = MonsterExtra.d2()
        self.d3 = MonsterExtra.d3()
        self.f0 = MonsterExtra.f0()
        self.f1 = MonsterExtra.f1()
        self.f2 = MonsterExtra.f2()
        self.f3 = MonsterExtra.f3()
        if not MonsterExtra.dvecIsNone():
            if np is None:
                self.dvec = []
                for i in range(MonsterExtra.dvecLength()):
                    self.dvec.append(MonsterExtra.dvec(i))
            else:
                self.dvec = MonsterExtra.dvecAsNumpy()
        if not MonsterExtra.fvecIsNone():
            if np is None:
                self.fvec = []
                for i in range(MonsterExtra.fvecLength()):
                    self.fvec.append(MonsterExtra.fvec(i))
            else:
                self.fvec = MonsterExtra.fvecAsNumpy()

    # MonsterExtraT
    def Pack(self, builder):
        if self.dvec is not None:
            if np is not None and type(self.dvec) is np.ndarray:
                dvec = builder.CreateNumpyVector(self.dvec)
            else:
                MonsterExtraStartdvecVector(builder, len(self.dvec))
                for i in reversed(range(len(self.dvec))):
                    builder.PrependFloat64(self.dvec[i])
                dvec = builder.EndVector()
        if self.fvec is not None:
            if np is not None and type(self.fvec) is np.ndarray:
                fvec = builder.CreateNumpyVector(self.fvec)
            else:
                MonsterExtraStartfvecVector(builder, len(self.fvec))
                for i in reversed(range(len(self.fvec))):
                    builder.PrependFloat32(self.fvec[i])
                fvec = builder.EndVector()
        MonsterExtraStart(builder)
        MonsterExtraAddd0(builder, self.d0)
        MonsterExtraAddd1(builder, self.d1)
        MonsterExtraAddd2(builder, self.d2)
        MonsterExtraAddd3(builder, self.d3)
        MonsterExtraAddf0(builder, self.f0)
        MonsterExtraAddf1(builder, self.f1)
        MonsterExtraAddf2(builder, self.f2)
        MonsterExtraAddf3(builder, self.f3)
        if self.dvec is not None:
            MonsterExtraAdddvec(builder, dvec)
        if self.fvec is not None:
            MonsterExtraAddfvec(builder, fvec)
        MonsterExtra = MonsterExtraEnd(builder)
        return MonsterExtra
