# automatically generated by the FlatBuffers compiler, do not modify

# namespace: EncryptionTest

import flatbuffers
from flatbuffers.compat import import_numpy
from .FlatbuffersEncryption import FlatbuffersEncryption
np = import_numpy()

class SensorReading(object):
    __slots__ = ['_tab', '_encryption_ctx']

    @classmethod
    def GetRootAs(cls, buf, offset=0, encryption_ctx=None):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SensorReading()
        x.Init(buf, n + offset, encryption_ctx)
        return x

    @classmethod
    def GetRootAsSensorReading(cls, buf, offset=0, encryption_ctx=None):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset, encryption_ctx)
    # SensorReading
    def Init(self, buf, pos, encryption_ctx=None):
        self._tab = flatbuffers.table.Table(buf, pos)
        self._encryption_ctx = encryption_ctx

    # SensorReading
    def DeviceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SensorReading
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # SensorReading
    def PublicData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from EncryptionTest.PublicData import PublicData
            obj = PublicData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorReading
    def Location(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from EncryptionTest.Coordinates import Coordinates
            obj = Coordinates()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorReading
    def Temperature(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return FlatbuffersEncryption.decrypt_scalar(self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos), self._encryption_ctx, 12)
        return 0.0

    # SensorReading
    def RawData(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # SensorReading
    def RawDataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # SensorReading
    def RawDataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorReading
    def RawDataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # SensorReading
    def SecretMessage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return FlatbuffersEncryption.decrypt_string(self._tab.String(o + self._tab.Pos), self._encryption_ctx, 16)
        return None

    # SensorReading
    def Readings(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # SensorReading
    def ReadingsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # SensorReading
    def ReadingsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorReading
    def ReadingsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

def SensorReadingStart(builder):
    builder.StartObject(8)

def Start(builder):
    SensorReadingStart(builder)

def SensorReadingAddDeviceId(builder, deviceId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(deviceId), 0)

def AddDeviceId(builder, deviceId):
    SensorReadingAddDeviceId(builder, deviceId)

def SensorReadingAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(1, timestamp, 0)

def AddTimestamp(builder, timestamp):
    SensorReadingAddTimestamp(builder, timestamp)

def SensorReadingAddPublicData(builder, publicData):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(publicData), 0)

def AddPublicData(builder, publicData):
    SensorReadingAddPublicData(builder, publicData)

def SensorReadingAddLocation(builder, location):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(location), 0)

def AddLocation(builder, location):
    SensorReadingAddLocation(builder, location)

def SensorReadingAddTemperature(builder, temperature):
    builder.PrependFloat32Slot(4, temperature, 0.0)

def AddTemperature(builder, temperature):
    SensorReadingAddTemperature(builder, temperature)

def SensorReadingAddRawData(builder, rawData):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(rawData), 0)

def AddRawData(builder, rawData):
    SensorReadingAddRawData(builder, rawData)

def SensorReadingStartRawDataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartRawDataVector(builder, numElems):
    return SensorReadingStartRawDataVector(builder, numElems)

def SensorReadingCreateRawDataVector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependUint8(item)
    return builder.EndVector()

def CreateRawDataVector(builder, data):
    SensorReadingCreateRawDataVector(builder, data)

def SensorReadingAddSecretMessage(builder, secretMessage):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(secretMessage), 0)

def AddSecretMessage(builder, secretMessage):
    SensorReadingAddSecretMessage(builder, secretMessage)

def SensorReadingAddReadings(builder, readings):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(readings), 0)

def AddReadings(builder, readings):
    SensorReadingAddReadings(builder, readings)

def SensorReadingStartReadingsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartReadingsVector(builder, numElems):
    return SensorReadingStartReadingsVector(builder, numElems)

def SensorReadingCreateReadingsVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependFloat32(item)
    return builder.EndVector()

def CreateReadingsVector(builder, data):
    SensorReadingCreateReadingsVector(builder, data)

def SensorReadingEnd(builder):
    return builder.EndObject()

def End(builder):
    return SensorReadingEnd(builder)
