from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from MyGame.Example.ArrayStruct import ArrayStruct
from MyGame.Example.NestedStruct import NestedStruct, NestedStructT
from MyGame.Example.TestEnum import TestEnum

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ArrayStruct(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def a(self) -> float: ...
  def b(self, i: int) -> typing.List[int]: ...
  def bAsNumpy(self) -> np.ndarray: ...
  def bLength(self) -> int: ...
  def bIsNone(self) -> bool: ...
  def c(self) -> int: ...
  def d(self, i: int) -> NestedStruct | None: ...
  def dLength(self) -> int: ...
  def dIsNone(self) -> bool: ...
  def e(self) -> int: ...
  def f(self, i: int) -> typing.List[int]: ...
  def fAsNumpy(self) -> np.ndarray: ...
  def fLength(self) -> int: ...
  def fIsNone(self) -> bool: ...
class ArrayStructT(object):
  a: float
  b: typing.List[int]
  c: int
  d: typing.List[NestedStructT]
  e: int
  f: typing.List[int]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> ArrayStructT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> ArrayStructT: ...
  @classmethod
  def InitFromObj(cls, ArrayStruct: ArrayStruct) -> ArrayStructT: ...
  def _UnPack(self, ArrayStruct: ArrayStruct) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...

def CreateArrayStruct(builder: flatbuffers.Builder, a: float, b: int, c: int, d_a: int, d_b: typing.Literal[TestEnum.A, TestEnum.B, TestEnum.C], d_c: typing.Literal[TestEnum.A, TestEnum.B, TestEnum.C], d_d: int, e: int, f: int) -> uoffset: ...

