# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Example

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# an example documentation comment: "monster object"
class Monster(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Monster()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMonster(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MonsterBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x4E\x53", size_prefixed=size_prefixed)

    # Monster
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Monster
    def Pos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from MyGame.Example.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Monster
    def Mana(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 150

    # Monster
    def Hp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 100

    # Monster
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Monster
    def Inventory(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Monster
    def InventoryAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Monster
    def InventoryLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def InventoryIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # Monster
    def Color(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 8

    # Monster
    def TestType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Monster
    def Test(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # Monster
    def Test4(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            from MyGame.Example.Test import Test
            obj = Test()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Monster
    def Test4Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def Test4IsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # Monster
    def Testarrayofstring(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # Monster
    def TestarrayofstringLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def TestarrayofstringIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

    # an example documentation comment: this will end up in the generated code
    # multiline too
    # Monster
    def Testarrayoftables(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MyGame.Example.Monster import Monster
            obj = Monster()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Monster
    def TestarrayoftablesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def TestarrayoftablesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        return o == 0

    # Monster
    def Enemy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MyGame.Example.Monster import Monster
            obj = Monster()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Monster
    def Testnestedflatbuffer(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Monster
    def TestnestedflatbufferAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Monster
    def TestnestedflatbufferNestedRoot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            from MyGame.Example.Monster import Monster
            return Monster.GetRootAs(self._tab.Bytes, self._tab.Vector(o))
        return 0

    # Monster
    def TestnestedflatbufferLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def TestnestedflatbufferIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        return o == 0

    # Monster
    def Testempty(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MyGame.Example.Stat import Stat
            obj = Stat()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Monster
    def Testbool(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Monster
    def Testhashs32Fnv1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Monster
    def Testhashu32Fnv1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Monster
    def Testhashs64Fnv1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Monster
    def Testhashu64Fnv1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Monster
    def Testhashs32Fnv1a(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Monster
    def Testhashu32Fnv1a(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Monster
    def Testhashs64Fnv1a(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Monster
    def Testhashu64Fnv1a(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Monster
    def Testarrayofbools(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Monster
    def TestarrayofboolsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.BoolFlags, o)
        return 0

    # Monster
    def TestarrayofboolsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def TestarrayofboolsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        return o == 0

    # Monster
    def Testf(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 3.14159

    # Monster
    def Testf2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 3.0

    # Monster
    def Testf3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Monster
    def Testarrayofstring2(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # Monster
    def Testarrayofstring2Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def Testarrayofstring2IsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        return o == 0

    # Monster
    def Testarrayofsortedstruct(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from MyGame.Example.Ability import Ability
            obj = Ability()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Monster
    def TestarrayofsortedstructLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def TestarrayofsortedstructIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        return o == 0

    # Monster
    def Flex(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Monster
    def FlexAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Monster
    def FlexLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def FlexIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        return o == 0

    # Monster
    def Test5(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            from MyGame.Example.Test import Test
            obj = Test()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Monster
    def Test5Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def Test5IsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        return o == 0

    # Monster
    def VectorOfLongs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Monster
    def VectorOfLongsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # Monster
    def VectorOfLongsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def VectorOfLongsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        return o == 0

    # Monster
    def VectorOfDoubles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Monster
    def VectorOfDoublesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # Monster
    def VectorOfDoublesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def VectorOfDoublesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        return o == 0

    # Monster
    def ParentNamespaceTest(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(72))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MyGame.InParentNamespace import InParentNamespace
            obj = InParentNamespace()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Monster
    def VectorOfReferrables(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(74))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MyGame.Example.Referrable import Referrable
            obj = Referrable()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Monster
    def VectorOfReferrablesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(74))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def VectorOfReferrablesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(74))
        return o == 0

    # Monster
    def SingleWeakReference(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(76))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Monster
    def VectorOfWeakReferences(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(78))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Monster
    def VectorOfWeakReferencesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(78))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # Monster
    def VectorOfWeakReferencesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(78))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def VectorOfWeakReferencesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(78))
        return o == 0

    # Monster
    def VectorOfStrongReferrables(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(80))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MyGame.Example.Referrable import Referrable
            obj = Referrable()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Monster
    def VectorOfStrongReferrablesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(80))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def VectorOfStrongReferrablesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(80))
        return o == 0

    # Monster
    def CoOwningReference(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(82))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Monster
    def VectorOfCoOwningReferences(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(84))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Monster
    def VectorOfCoOwningReferencesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(84))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # Monster
    def VectorOfCoOwningReferencesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(84))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def VectorOfCoOwningReferencesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(84))
        return o == 0

    # Monster
    def NonOwningReference(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(86))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Monster
    def VectorOfNonOwningReferences(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(88))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Monster
    def VectorOfNonOwningReferencesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(88))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # Monster
    def VectorOfNonOwningReferencesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(88))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def VectorOfNonOwningReferencesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(88))
        return o == 0

    # Monster
    def AnyUniqueType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(90))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Monster
    def AnyUnique(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(92))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # Monster
    def AnyAmbiguousType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(94))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Monster
    def AnyAmbiguous(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(96))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # Monster
    def VectorOfEnums(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(98))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Monster
    def VectorOfEnumsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(98))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Monster
    def VectorOfEnumsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(98))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def VectorOfEnumsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(98))
        return o == 0

    # Monster
    def SignedEnum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(100))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return -1

    # Monster
    def Testrequirednestedflatbuffer(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(102))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Monster
    def TestrequirednestedflatbufferAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(102))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Monster
    def TestrequirednestedflatbufferNestedRoot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(102))
        if o != 0:
            from MyGame.Example.Monster import Monster
            return Monster.GetRootAs(self._tab.Bytes, self._tab.Vector(o))
        return 0

    # Monster
    def TestrequirednestedflatbufferLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(102))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def TestrequirednestedflatbufferIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(102))
        return o == 0

    # Monster
    def ScalarKeySortedTables(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(104))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MyGame.Example.Stat import Stat
            obj = Stat()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Monster
    def ScalarKeySortedTablesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(104))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Monster
    def ScalarKeySortedTablesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(104))
        return o == 0

    # Monster
    def NativeInline(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(106))
        if o != 0:
            x = o + self._tab.Pos
            from MyGame.Example.Test import Test
            obj = Test()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Monster
    def LongEnumNonEnumDefault(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(108))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Monster
    def LongEnumNormalDefault(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(110))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 2

    # Monster
    def NanDefault(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(112))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return float('nan')

    # Monster
    def InfDefault(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(114))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return float('inf')

    # Monster
    def PositiveInfDefault(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(116))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return float('inf')

    # Monster
    def InfinityDefault(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(118))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return float('inf')

    # Monster
    def PositiveInfinityDefault(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(120))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return float('inf')

    # Monster
    def NegativeInfDefault(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(122))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return float('-inf')

    # Monster
    def NegativeInfinityDefault(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(124))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return float('-inf')

    # Monster
    def DoubleInfDefault(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(126))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return float('inf')

def MonsterStart(builder):
    builder.StartObject(62)

def Start(builder):
    MonsterStart(builder)

def MonsterAddPos(builder, pos):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(pos), 0)

def AddPos(builder, pos):
    MonsterAddPos(builder, pos)

def MonsterAddMana(builder, mana):
    builder.PrependInt16Slot(1, mana, 150)

def AddMana(builder, mana):
    MonsterAddMana(builder, mana)

def MonsterAddHp(builder, hp):
    builder.PrependInt16Slot(2, hp, 100)

def AddHp(builder, hp):
    MonsterAddHp(builder, hp)

def MonsterAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    MonsterAddName(builder, name)

def MonsterAddInventory(builder, inventory):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(inventory), 0)

def AddInventory(builder, inventory):
    MonsterAddInventory(builder, inventory)

def MonsterStartInventoryVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartInventoryVector(builder, numElems):
    return MonsterStartInventoryVector(builder, numElems)

def MonsterAddColor(builder, color):
    builder.PrependUint8Slot(6, color, 8)

def AddColor(builder, color):
    MonsterAddColor(builder, color)

def MonsterAddTestType(builder, testType):
    builder.PrependUint8Slot(7, testType, 0)

def AddTestType(builder, testType):
    MonsterAddTestType(builder, testType)

def MonsterAddTest(builder, test):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(test), 0)

def AddTest(builder, test):
    MonsterAddTest(builder, test)

def MonsterAddTest4(builder, test4):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(test4), 0)

def AddTest4(builder, test4):
    MonsterAddTest4(builder, test4)

def MonsterStartTest4Vector(builder, numElems):
    return builder.StartVector(4, numElems, 2)

def StartTest4Vector(builder, numElems):
    return MonsterStartTest4Vector(builder, numElems)

def MonsterAddTestarrayofstring(builder, testarrayofstring):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(testarrayofstring), 0)

def AddTestarrayofstring(builder, testarrayofstring):
    MonsterAddTestarrayofstring(builder, testarrayofstring)

def MonsterStartTestarrayofstringVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTestarrayofstringVector(builder, numElems):
    return MonsterStartTestarrayofstringVector(builder, numElems)

def MonsterAddTestarrayoftables(builder, testarrayoftables):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(testarrayoftables), 0)

def AddTestarrayoftables(builder, testarrayoftables):
    MonsterAddTestarrayoftables(builder, testarrayoftables)

def MonsterStartTestarrayoftablesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTestarrayoftablesVector(builder, numElems):
    return MonsterStartTestarrayoftablesVector(builder, numElems)

def MonsterAddEnemy(builder, enemy):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(enemy), 0)

def AddEnemy(builder, enemy):
    MonsterAddEnemy(builder, enemy)

def MonsterAddTestnestedflatbuffer(builder, testnestedflatbuffer):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(testnestedflatbuffer), 0)

def AddTestnestedflatbuffer(builder, testnestedflatbuffer):
    MonsterAddTestnestedflatbuffer(builder, testnestedflatbuffer)

def MonsterStartTestnestedflatbufferVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartTestnestedflatbufferVector(builder, numElems):
    return MonsterStartTestnestedflatbufferVector(builder, numElems)

def MonsterMakeTestnestedflatbufferVectorFromBytes(builder, bytes):
    builder.StartVector(1, len(bytes), 1)
    builder.head = builder.head - len(bytes)
    builder.Bytes[builder.head : builder.head + len(bytes)] = bytes
    return builder.EndVector()
def MakeTestnestedflatbufferVectorFromBytes(builder, bytes):
    return MonsterMakeTestnestedflatbufferVectorFromBytes(builder, bytes)
def MonsterAddTestempty(builder, testempty):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(testempty), 0)

def AddTestempty(builder, testempty):
    MonsterAddTestempty(builder, testempty)

def MonsterAddTestbool(builder, testbool):
    builder.PrependBoolSlot(15, testbool, 0)

def AddTestbool(builder, testbool):
    MonsterAddTestbool(builder, testbool)

def MonsterAddTesthashs32Fnv1(builder, testhashs32_fnv1):
    builder.PrependInt32Slot(16, testhashs32_fnv1, 0)

def AddTesthashs32Fnv1(builder, testhashs32_fnv1):
    MonsterAddTesthashs32Fnv1(builder, testhashs32_fnv1)

def MonsterAddTesthashu32Fnv1(builder, testhashu32_fnv1):
    builder.PrependUint32Slot(17, testhashu32_fnv1, 0)

def AddTesthashu32Fnv1(builder, testhashu32_fnv1):
    MonsterAddTesthashu32Fnv1(builder, testhashu32_fnv1)

def MonsterAddTesthashs64Fnv1(builder, testhashs64_fnv1):
    builder.PrependInt64Slot(18, testhashs64_fnv1, 0)

def AddTesthashs64Fnv1(builder, testhashs64_fnv1):
    MonsterAddTesthashs64Fnv1(builder, testhashs64_fnv1)

def MonsterAddTesthashu64Fnv1(builder, testhashu64_fnv1):
    builder.PrependUint64Slot(19, testhashu64_fnv1, 0)

def AddTesthashu64Fnv1(builder, testhashu64_fnv1):
    MonsterAddTesthashu64Fnv1(builder, testhashu64_fnv1)

def MonsterAddTesthashs32Fnv1a(builder, testhashs32_fnv1a):
    builder.PrependInt32Slot(20, testhashs32_fnv1a, 0)

def AddTesthashs32Fnv1a(builder, testhashs32_fnv1a):
    MonsterAddTesthashs32Fnv1a(builder, testhashs32_fnv1a)

def MonsterAddTesthashu32Fnv1a(builder, testhashu32_fnv1a):
    builder.PrependUint32Slot(21, testhashu32_fnv1a, 0)

def AddTesthashu32Fnv1a(builder, testhashu32_fnv1a):
    MonsterAddTesthashu32Fnv1a(builder, testhashu32_fnv1a)

def MonsterAddTesthashs64Fnv1a(builder, testhashs64_fnv1a):
    builder.PrependInt64Slot(22, testhashs64_fnv1a, 0)

def AddTesthashs64Fnv1a(builder, testhashs64_fnv1a):
    MonsterAddTesthashs64Fnv1a(builder, testhashs64_fnv1a)

def MonsterAddTesthashu64Fnv1a(builder, testhashu64_fnv1a):
    builder.PrependUint64Slot(23, testhashu64_fnv1a, 0)

def AddTesthashu64Fnv1a(builder, testhashu64_fnv1a):
    MonsterAddTesthashu64Fnv1a(builder, testhashu64_fnv1a)

def MonsterAddTestarrayofbools(builder, testarrayofbools):
    builder.PrependUOffsetTRelativeSlot(24, flatbuffers.number_types.UOffsetTFlags.py_type(testarrayofbools), 0)

def AddTestarrayofbools(builder, testarrayofbools):
    MonsterAddTestarrayofbools(builder, testarrayofbools)

def MonsterStartTestarrayofboolsVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartTestarrayofboolsVector(builder, numElems):
    return MonsterStartTestarrayofboolsVector(builder, numElems)

def MonsterAddTestf(builder, testf):
    builder.PrependFloat32Slot(25, testf, 3.14159)

def AddTestf(builder, testf):
    MonsterAddTestf(builder, testf)

def MonsterAddTestf2(builder, testf2):
    builder.PrependFloat32Slot(26, testf2, 3.0)

def AddTestf2(builder, testf2):
    MonsterAddTestf2(builder, testf2)

def MonsterAddTestf3(builder, testf3):
    builder.PrependFloat32Slot(27, testf3, 0.0)

def AddTestf3(builder, testf3):
    MonsterAddTestf3(builder, testf3)

def MonsterAddTestarrayofstring2(builder, testarrayofstring2):
    builder.PrependUOffsetTRelativeSlot(28, flatbuffers.number_types.UOffsetTFlags.py_type(testarrayofstring2), 0)

def AddTestarrayofstring2(builder, testarrayofstring2):
    MonsterAddTestarrayofstring2(builder, testarrayofstring2)

def MonsterStartTestarrayofstring2Vector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTestarrayofstring2Vector(builder, numElems):
    return MonsterStartTestarrayofstring2Vector(builder, numElems)

def MonsterAddTestarrayofsortedstruct(builder, testarrayofsortedstruct):
    builder.PrependUOffsetTRelativeSlot(29, flatbuffers.number_types.UOffsetTFlags.py_type(testarrayofsortedstruct), 0)

def AddTestarrayofsortedstruct(builder, testarrayofsortedstruct):
    MonsterAddTestarrayofsortedstruct(builder, testarrayofsortedstruct)

def MonsterStartTestarrayofsortedstructVector(builder, numElems):
    return builder.StartVector(8, numElems, 4)

def StartTestarrayofsortedstructVector(builder, numElems):
    return MonsterStartTestarrayofsortedstructVector(builder, numElems)

def MonsterAddFlex(builder, flex):
    builder.PrependUOffsetTRelativeSlot(30, flatbuffers.number_types.UOffsetTFlags.py_type(flex), 0)

def AddFlex(builder, flex):
    MonsterAddFlex(builder, flex)

def MonsterStartFlexVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartFlexVector(builder, numElems):
    return MonsterStartFlexVector(builder, numElems)

def MonsterAddTest5(builder, test5):
    builder.PrependUOffsetTRelativeSlot(31, flatbuffers.number_types.UOffsetTFlags.py_type(test5), 0)

def AddTest5(builder, test5):
    MonsterAddTest5(builder, test5)

def MonsterStartTest5Vector(builder, numElems):
    return builder.StartVector(4, numElems, 2)

def StartTest5Vector(builder, numElems):
    return MonsterStartTest5Vector(builder, numElems)

def MonsterAddVectorOfLongs(builder, vector_of_longs):
    builder.PrependUOffsetTRelativeSlot(32, flatbuffers.number_types.UOffsetTFlags.py_type(vector_of_longs), 0)

def AddVectorOfLongs(builder, vector_of_longs):
    MonsterAddVectorOfLongs(builder, vector_of_longs)

def MonsterStartVectorOfLongsVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartVectorOfLongsVector(builder, numElems):
    return MonsterStartVectorOfLongsVector(builder, numElems)

def MonsterAddVectorOfDoubles(builder, vector_of_doubles):
    builder.PrependUOffsetTRelativeSlot(33, flatbuffers.number_types.UOffsetTFlags.py_type(vector_of_doubles), 0)

def AddVectorOfDoubles(builder, vector_of_doubles):
    MonsterAddVectorOfDoubles(builder, vector_of_doubles)

def MonsterStartVectorOfDoublesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartVectorOfDoublesVector(builder, numElems):
    return MonsterStartVectorOfDoublesVector(builder, numElems)

def MonsterAddParentNamespaceTest(builder, parent_namespace_test):
    builder.PrependUOffsetTRelativeSlot(34, flatbuffers.number_types.UOffsetTFlags.py_type(parent_namespace_test), 0)

def AddParentNamespaceTest(builder, parent_namespace_test):
    MonsterAddParentNamespaceTest(builder, parent_namespace_test)

def MonsterAddVectorOfReferrables(builder, vector_of_referrables):
    builder.PrependUOffsetTRelativeSlot(35, flatbuffers.number_types.UOffsetTFlags.py_type(vector_of_referrables), 0)

def AddVectorOfReferrables(builder, vector_of_referrables):
    MonsterAddVectorOfReferrables(builder, vector_of_referrables)

def MonsterStartVectorOfReferrablesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartVectorOfReferrablesVector(builder, numElems):
    return MonsterStartVectorOfReferrablesVector(builder, numElems)

def MonsterAddSingleWeakReference(builder, single_weak_reference):
    builder.PrependUint64Slot(36, single_weak_reference, 0)

def AddSingleWeakReference(builder, single_weak_reference):
    MonsterAddSingleWeakReference(builder, single_weak_reference)

def MonsterAddVectorOfWeakReferences(builder, vector_of_weak_references):
    builder.PrependUOffsetTRelativeSlot(37, flatbuffers.number_types.UOffsetTFlags.py_type(vector_of_weak_references), 0)

def AddVectorOfWeakReferences(builder, vector_of_weak_references):
    MonsterAddVectorOfWeakReferences(builder, vector_of_weak_references)

def MonsterStartVectorOfWeakReferencesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartVectorOfWeakReferencesVector(builder, numElems):
    return MonsterStartVectorOfWeakReferencesVector(builder, numElems)

def MonsterAddVectorOfStrongReferrables(builder, vector_of_strong_referrables):
    builder.PrependUOffsetTRelativeSlot(38, flatbuffers.number_types.UOffsetTFlags.py_type(vector_of_strong_referrables), 0)

def AddVectorOfStrongReferrables(builder, vector_of_strong_referrables):
    MonsterAddVectorOfStrongReferrables(builder, vector_of_strong_referrables)

def MonsterStartVectorOfStrongReferrablesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartVectorOfStrongReferrablesVector(builder, numElems):
    return MonsterStartVectorOfStrongReferrablesVector(builder, numElems)

def MonsterAddCoOwningReference(builder, co_owning_reference):
    builder.PrependUint64Slot(39, co_owning_reference, 0)

def AddCoOwningReference(builder, co_owning_reference):
    MonsterAddCoOwningReference(builder, co_owning_reference)

def MonsterAddVectorOfCoOwningReferences(builder, vector_of_co_owning_references):
    builder.PrependUOffsetTRelativeSlot(40, flatbuffers.number_types.UOffsetTFlags.py_type(vector_of_co_owning_references), 0)

def AddVectorOfCoOwningReferences(builder, vector_of_co_owning_references):
    MonsterAddVectorOfCoOwningReferences(builder, vector_of_co_owning_references)

def MonsterStartVectorOfCoOwningReferencesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartVectorOfCoOwningReferencesVector(builder, numElems):
    return MonsterStartVectorOfCoOwningReferencesVector(builder, numElems)

def MonsterAddNonOwningReference(builder, non_owning_reference):
    builder.PrependUint64Slot(41, non_owning_reference, 0)

def AddNonOwningReference(builder, non_owning_reference):
    MonsterAddNonOwningReference(builder, non_owning_reference)

def MonsterAddVectorOfNonOwningReferences(builder, vector_of_non_owning_references):
    builder.PrependUOffsetTRelativeSlot(42, flatbuffers.number_types.UOffsetTFlags.py_type(vector_of_non_owning_references), 0)

def AddVectorOfNonOwningReferences(builder, vector_of_non_owning_references):
    MonsterAddVectorOfNonOwningReferences(builder, vector_of_non_owning_references)

def MonsterStartVectorOfNonOwningReferencesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartVectorOfNonOwningReferencesVector(builder, numElems):
    return MonsterStartVectorOfNonOwningReferencesVector(builder, numElems)

def MonsterAddAnyUniqueType(builder, anyUniqueType):
    builder.PrependUint8Slot(43, anyUniqueType, 0)

def AddAnyUniqueType(builder, anyUniqueType):
    MonsterAddAnyUniqueType(builder, anyUniqueType)

def MonsterAddAnyUnique(builder, any_unique):
    builder.PrependUOffsetTRelativeSlot(44, flatbuffers.number_types.UOffsetTFlags.py_type(any_unique), 0)

def AddAnyUnique(builder, any_unique):
    MonsterAddAnyUnique(builder, any_unique)

def MonsterAddAnyAmbiguousType(builder, anyAmbiguousType):
    builder.PrependUint8Slot(45, anyAmbiguousType, 0)

def AddAnyAmbiguousType(builder, anyAmbiguousType):
    MonsterAddAnyAmbiguousType(builder, anyAmbiguousType)

def MonsterAddAnyAmbiguous(builder, any_ambiguous):
    builder.PrependUOffsetTRelativeSlot(46, flatbuffers.number_types.UOffsetTFlags.py_type(any_ambiguous), 0)

def AddAnyAmbiguous(builder, any_ambiguous):
    MonsterAddAnyAmbiguous(builder, any_ambiguous)

def MonsterAddVectorOfEnums(builder, vector_of_enums):
    builder.PrependUOffsetTRelativeSlot(47, flatbuffers.number_types.UOffsetTFlags.py_type(vector_of_enums), 0)

def AddVectorOfEnums(builder, vector_of_enums):
    MonsterAddVectorOfEnums(builder, vector_of_enums)

def MonsterStartVectorOfEnumsVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartVectorOfEnumsVector(builder, numElems):
    return MonsterStartVectorOfEnumsVector(builder, numElems)

def MonsterAddSignedEnum(builder, signed_enum):
    builder.PrependInt8Slot(48, signed_enum, -1)

def AddSignedEnum(builder, signed_enum):
    MonsterAddSignedEnum(builder, signed_enum)

def MonsterAddTestrequirednestedflatbuffer(builder, testrequirednestedflatbuffer):
    builder.PrependUOffsetTRelativeSlot(49, flatbuffers.number_types.UOffsetTFlags.py_type(testrequirednestedflatbuffer), 0)

def AddTestrequirednestedflatbuffer(builder, testrequirednestedflatbuffer):
    MonsterAddTestrequirednestedflatbuffer(builder, testrequirednestedflatbuffer)

def MonsterStartTestrequirednestedflatbufferVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartTestrequirednestedflatbufferVector(builder, numElems):
    return MonsterStartTestrequirednestedflatbufferVector(builder, numElems)

def MonsterMakeTestrequirednestedflatbufferVectorFromBytes(builder, bytes):
    builder.StartVector(1, len(bytes), 1)
    builder.head = builder.head - len(bytes)
    builder.Bytes[builder.head : builder.head + len(bytes)] = bytes
    return builder.EndVector()
def MakeTestrequirednestedflatbufferVectorFromBytes(builder, bytes):
    return MonsterMakeTestrequirednestedflatbufferVectorFromBytes(builder, bytes)
def MonsterAddScalarKeySortedTables(builder, scalar_key_sorted_tables):
    builder.PrependUOffsetTRelativeSlot(50, flatbuffers.number_types.UOffsetTFlags.py_type(scalar_key_sorted_tables), 0)

def AddScalarKeySortedTables(builder, scalar_key_sorted_tables):
    MonsterAddScalarKeySortedTables(builder, scalar_key_sorted_tables)

def MonsterStartScalarKeySortedTablesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartScalarKeySortedTablesVector(builder, numElems):
    return MonsterStartScalarKeySortedTablesVector(builder, numElems)

def MonsterAddNativeInline(builder, native_inline):
    builder.PrependStructSlot(51, flatbuffers.number_types.UOffsetTFlags.py_type(native_inline), 0)

def AddNativeInline(builder, native_inline):
    MonsterAddNativeInline(builder, native_inline)

def MonsterAddLongEnumNonEnumDefault(builder, long_enum_non_enum_default):
    builder.PrependUint64Slot(52, long_enum_non_enum_default, 0)

def AddLongEnumNonEnumDefault(builder, long_enum_non_enum_default):
    MonsterAddLongEnumNonEnumDefault(builder, long_enum_non_enum_default)

def MonsterAddLongEnumNormalDefault(builder, long_enum_normal_default):
    builder.PrependUint64Slot(53, long_enum_normal_default, 2)

def AddLongEnumNormalDefault(builder, long_enum_normal_default):
    MonsterAddLongEnumNormalDefault(builder, long_enum_normal_default)

def MonsterAddNanDefault(builder, nan_default):
    builder.PrependFloat32Slot(54, nan_default, float('nan'))

def AddNanDefault(builder, nan_default):
    MonsterAddNanDefault(builder, nan_default)

def MonsterAddInfDefault(builder, inf_default):
    builder.PrependFloat32Slot(55, inf_default, float('inf'))

def AddInfDefault(builder, inf_default):
    MonsterAddInfDefault(builder, inf_default)

def MonsterAddPositiveInfDefault(builder, positive_inf_default):
    builder.PrependFloat32Slot(56, positive_inf_default, float('inf'))

def AddPositiveInfDefault(builder, positive_inf_default):
    MonsterAddPositiveInfDefault(builder, positive_inf_default)

def MonsterAddInfinityDefault(builder, infinity_default):
    builder.PrependFloat32Slot(57, infinity_default, float('inf'))

def AddInfinityDefault(builder, infinity_default):
    MonsterAddInfinityDefault(builder, infinity_default)

def MonsterAddPositiveInfinityDefault(builder, positive_infinity_default):
    builder.PrependFloat32Slot(58, positive_infinity_default, float('inf'))

def AddPositiveInfinityDefault(builder, positive_infinity_default):
    MonsterAddPositiveInfinityDefault(builder, positive_infinity_default)

def MonsterAddNegativeInfDefault(builder, negative_inf_default):
    builder.PrependFloat32Slot(59, negative_inf_default, float('-inf'))

def AddNegativeInfDefault(builder, negative_inf_default):
    MonsterAddNegativeInfDefault(builder, negative_inf_default)

def MonsterAddNegativeInfinityDefault(builder, negative_infinity_default):
    builder.PrependFloat32Slot(60, negative_infinity_default, float('-inf'))

def AddNegativeInfinityDefault(builder, negative_infinity_default):
    MonsterAddNegativeInfinityDefault(builder, negative_infinity_default)

def MonsterAddDoubleInfDefault(builder, double_inf_default):
    builder.PrependFloat64Slot(61, double_inf_default, float('inf'))

def AddDoubleInfDefault(builder, double_inf_default):
    MonsterAddDoubleInfDefault(builder, double_inf_default)

def MonsterEnd(builder):
    return builder.EndObject()

def End(builder):
    return MonsterEnd(builder)

import MyGame.Example.Ability
import MyGame.Example.Any
import MyGame.Example.AnyAmbiguousAliases
import MyGame.Example.AnyUniqueAliases
import MyGame.Example.Referrable
import MyGame.Example.Stat
import MyGame.Example.Test
import MyGame.Example.TestSimpleTableWithEnum
import MyGame.Example.Vec3
import MyGame.Example2.Monster
import MyGame.InParentNamespace
try:
    from typing import List, Optional, Union
except:
    pass

class MonsterT(object):

    # MonsterT
    def __init__(self):
        self.pos = None  # type: Optional[MyGame.Example.Vec3.Vec3T]
        self.mana = 150  # type: int
        self.hp = 100  # type: int
        self.name = None  # type: str
        self.inventory = None  # type: List[int]
        self.color = 8  # type: int
        self.testType = 0  # type: int
        self.test = None  # type: Union[None, MyGame.Example.Monster.MonsterT, MyGame.Example.TestSimpleTableWithEnum.TestSimpleTableWithEnumT, MyGame.Example2.Monster.MonsterT]
        self.test4 = None  # type: List[MyGame.Example.Test.TestT]
        self.testarrayofstring = None  # type: List[str]
        self.testarrayoftables = None  # type: List[MyGame.Example.Monster.MonsterT]
        self.enemy = None  # type: Optional[MyGame.Example.Monster.MonsterT]
        self.testnestedflatbuffer = None  # type: List[int]
        self.testempty = None  # type: Optional[MyGame.Example.Stat.StatT]
        self.testbool = False  # type: bool
        self.testhashs32_fnv1 = 0  # type: int
        self.testhashu32_fnv1 = 0  # type: int
        self.testhashs64_fnv1 = 0  # type: int
        self.testhashu64_fnv1 = 0  # type: int
        self.testhashs32_fnv1a = 0  # type: int
        self.testhashu32_fnv1a = 0  # type: int
        self.testhashs64_fnv1a = 0  # type: int
        self.testhashu64_fnv1a = 0  # type: int
        self.testarrayofbools = None  # type: List[bool]
        self.testf = 3.14159  # type: float
        self.testf2 = 3.0  # type: float
        self.testf3 = 0.0  # type: float
        self.testarrayofstring2 = None  # type: List[str]
        self.testarrayofsortedstruct = None  # type: List[MyGame.Example.Ability.AbilityT]
        self.flex = None  # type: List[int]
        self.test5 = None  # type: List[MyGame.Example.Test.TestT]
        self.vector_of_longs = None  # type: List[int]
        self.vector_of_doubles = None  # type: List[float]
        self.parent_namespace_test = None  # type: Optional[MyGame.InParentNamespace.InParentNamespaceT]
        self.vector_of_referrables = None  # type: List[MyGame.Example.Referrable.ReferrableT]
        self.single_weak_reference = 0  # type: int
        self.vector_of_weak_references = None  # type: List[int]
        self.vector_of_strong_referrables = None  # type: List[MyGame.Example.Referrable.ReferrableT]
        self.co_owning_reference = 0  # type: int
        self.vector_of_co_owning_references = None  # type: List[int]
        self.non_owning_reference = 0  # type: int
        self.vector_of_non_owning_references = None  # type: List[int]
        self.anyUniqueType = 0  # type: int
        self.any_unique = None  # type: Union[None, MyGame.Example.Monster.MonsterT, MyGame.Example.TestSimpleTableWithEnum.TestSimpleTableWithEnumT, MyGame.Example2.Monster.MonsterT]
        self.anyAmbiguousType = 0  # type: int
        self.any_ambiguous = None  # type: Union[None, MyGame.Example.Monster.MonsterT, MyGame.Example.Monster.MonsterT, MyGame.Example.Monster.MonsterT]
        self.vector_of_enums = None  # type: List[int]
        self.signed_enum = -1  # type: int
        self.testrequirednestedflatbuffer = None  # type: List[int]
        self.scalar_key_sorted_tables = None  # type: List[MyGame.Example.Stat.StatT]
        self.native_inline = None  # type: Optional[MyGame.Example.Test.TestT]
        self.long_enum_non_enum_default = 0  # type: int
        self.long_enum_normal_default = 2  # type: int
        self.nan_default = float('nan')  # type: float
        self.inf_default = float('inf')  # type: float
        self.positive_inf_default = float('inf')  # type: float
        self.infinity_default = float('inf')  # type: float
        self.positive_infinity_default = float('inf')  # type: float
        self.negative_inf_default = float('-inf')  # type: float
        self.negative_infinity_default = float('-inf')  # type: float
        self.double_inf_default = float('inf')  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        Monster = Monster()
        Monster.Init(buf, pos)
        return cls.InitFromObj(Monster)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, Monster):
        x = MonsterT()
        x._UnPack(Monster)
        return x

    # MonsterT
    def _UnPack(self, Monster):
        if Monster is None:
            return
        if Monster.Pos() is not None:
            self.pos = MyGame.Example.Vec3.Vec3T.InitFromObj(Monster.Pos())
        self.mana = Monster.Mana()
        self.hp = Monster.Hp()
        self.name = Monster.Name()
        if not Monster.InventoryIsNone():
            if np is None:
                self.inventory = []
                for i in range(Monster.InventoryLength()):
                    self.inventory.append(Monster.Inventory(i))
            else:
                self.inventory = Monster.InventoryAsNumpy()
        self.color = Monster.Color()
        self.testType = Monster.TestType()
        self.test = MyGame.Example.Any.AnyCreator(self.testType, Monster.Test())
        if not Monster.Test4IsNone():
            self.test4 = []
            for i in range(Monster.Test4Length()):
                if Monster.Test4(i) is None:
                    self.test4.append(None)
                else:
                    test_ = MyGame.Example.Test.TestT.InitFromObj(Monster.Test4(i))
                    self.test4.append(test_)
        if not Monster.TestarrayofstringIsNone():
            self.testarrayofstring = []
            for i in range(Monster.TestarrayofstringLength()):
                self.testarrayofstring.append(Monster.Testarrayofstring(i))
        if not Monster.TestarrayoftablesIsNone():
            self.testarrayoftables = []
            for i in range(Monster.TestarrayoftablesLength()):
                if Monster.Testarrayoftables(i) is None:
                    self.testarrayoftables.append(None)
                else:
                    monster_ = MyGame.Example.Monster.MonsterT.InitFromObj(Monster.Testarrayoftables(i))
                    self.testarrayoftables.append(monster_)
        if Monster.Enemy() is not None:
            self.enemy = MyGame.Example.Monster.MonsterT.InitFromObj(Monster.Enemy())
        if not Monster.TestnestedflatbufferIsNone():
            if np is None:
                self.testnestedflatbuffer = []
                for i in range(Monster.TestnestedflatbufferLength()):
                    self.testnestedflatbuffer.append(Monster.Testnestedflatbuffer(i))
            else:
                self.testnestedflatbuffer = Monster.TestnestedflatbufferAsNumpy()
        if Monster.Testempty() is not None:
            self.testempty = MyGame.Example.Stat.StatT.InitFromObj(Monster.Testempty())
        self.testbool = Monster.Testbool()
        self.testhashs32_fnv1 = Monster.Testhashs32Fnv1()
        self.testhashu32_fnv1 = Monster.Testhashu32Fnv1()
        self.testhashs64_fnv1 = Monster.Testhashs64Fnv1()
        self.testhashu64_fnv1 = Monster.Testhashu64Fnv1()
        self.testhashs32_fnv1a = Monster.Testhashs32Fnv1a()
        self.testhashu32_fnv1a = Monster.Testhashu32Fnv1a()
        self.testhashs64_fnv1a = Monster.Testhashs64Fnv1a()
        self.testhashu64_fnv1a = Monster.Testhashu64Fnv1a()
        if not Monster.TestarrayofboolsIsNone():
            if np is None:
                self.testarrayofbools = []
                for i in range(Monster.TestarrayofboolsLength()):
                    self.testarrayofbools.append(Monster.Testarrayofbools(i))
            else:
                self.testarrayofbools = Monster.TestarrayofboolsAsNumpy()
        self.testf = Monster.Testf()
        self.testf2 = Monster.Testf2()
        self.testf3 = Monster.Testf3()
        if not Monster.Testarrayofstring2IsNone():
            self.testarrayofstring2 = []
            for i in range(Monster.Testarrayofstring2Length()):
                self.testarrayofstring2.append(Monster.Testarrayofstring2(i))
        if not Monster.TestarrayofsortedstructIsNone():
            self.testarrayofsortedstruct = []
            for i in range(Monster.TestarrayofsortedstructLength()):
                if Monster.Testarrayofsortedstruct(i) is None:
                    self.testarrayofsortedstruct.append(None)
                else:
                    ability_ = MyGame.Example.Ability.AbilityT.InitFromObj(Monster.Testarrayofsortedstruct(i))
                    self.testarrayofsortedstruct.append(ability_)
        if not Monster.FlexIsNone():
            if np is None:
                self.flex = []
                for i in range(Monster.FlexLength()):
                    self.flex.append(Monster.Flex(i))
            else:
                self.flex = Monster.FlexAsNumpy()
        if not Monster.Test5IsNone():
            self.test5 = []
            for i in range(Monster.Test5Length()):
                if Monster.Test5(i) is None:
                    self.test5.append(None)
                else:
                    test_ = MyGame.Example.Test.TestT.InitFromObj(Monster.Test5(i))
                    self.test5.append(test_)
        if not Monster.VectorOfLongsIsNone():
            if np is None:
                self.vector_of_longs = []
                for i in range(Monster.VectorOfLongsLength()):
                    self.vector_of_longs.append(Monster.VectorOfLongs(i))
            else:
                self.vector_of_longs = Monster.VectorOfLongsAsNumpy()
        if not Monster.VectorOfDoublesIsNone():
            if np is None:
                self.vector_of_doubles = []
                for i in range(Monster.VectorOfDoublesLength()):
                    self.vector_of_doubles.append(Monster.VectorOfDoubles(i))
            else:
                self.vector_of_doubles = Monster.VectorOfDoublesAsNumpy()
        if Monster.ParentNamespaceTest() is not None:
            self.parent_namespace_test = MyGame.InParentNamespace.InParentNamespaceT.InitFromObj(Monster.ParentNamespaceTest())
        if not Monster.VectorOfReferrablesIsNone():
            self.vector_of_referrables = []
            for i in range(Monster.VectorOfReferrablesLength()):
                if Monster.VectorOfReferrables(i) is None:
                    self.vector_of_referrables.append(None)
                else:
                    referrable_ = MyGame.Example.Referrable.ReferrableT.InitFromObj(Monster.VectorOfReferrables(i))
                    self.vector_of_referrables.append(referrable_)
        self.single_weak_reference = Monster.SingleWeakReference()
        if not Monster.VectorOfWeakReferencesIsNone():
            if np is None:
                self.vector_of_weak_references = []
                for i in range(Monster.VectorOfWeakReferencesLength()):
                    self.vector_of_weak_references.append(Monster.VectorOfWeakReferences(i))
            else:
                self.vector_of_weak_references = Monster.VectorOfWeakReferencesAsNumpy()
        if not Monster.VectorOfStrongReferrablesIsNone():
            self.vector_of_strong_referrables = []
            for i in range(Monster.VectorOfStrongReferrablesLength()):
                if Monster.VectorOfStrongReferrables(i) is None:
                    self.vector_of_strong_referrables.append(None)
                else:
                    referrable_ = MyGame.Example.Referrable.ReferrableT.InitFromObj(Monster.VectorOfStrongReferrables(i))
                    self.vector_of_strong_referrables.append(referrable_)
        self.co_owning_reference = Monster.CoOwningReference()
        if not Monster.VectorOfCoOwningReferencesIsNone():
            if np is None:
                self.vector_of_co_owning_references = []
                for i in range(Monster.VectorOfCoOwningReferencesLength()):
                    self.vector_of_co_owning_references.append(Monster.VectorOfCoOwningReferences(i))
            else:
                self.vector_of_co_owning_references = Monster.VectorOfCoOwningReferencesAsNumpy()
        self.non_owning_reference = Monster.NonOwningReference()
        if not Monster.VectorOfNonOwningReferencesIsNone():
            if np is None:
                self.vector_of_non_owning_references = []
                for i in range(Monster.VectorOfNonOwningReferencesLength()):
                    self.vector_of_non_owning_references.append(Monster.VectorOfNonOwningReferences(i))
            else:
                self.vector_of_non_owning_references = Monster.VectorOfNonOwningReferencesAsNumpy()
        self.anyUniqueType = Monster.AnyUniqueType()
        self.any_unique = MyGame.Example.AnyUniqueAliases.AnyUniqueAliasesCreator(self.any_uniqueType, Monster.AnyUnique())
        self.anyAmbiguousType = Monster.AnyAmbiguousType()
        self.any_ambiguous = MyGame.Example.AnyAmbiguousAliases.AnyAmbiguousAliasesCreator(self.any_ambiguousType, Monster.AnyAmbiguous())
        if not Monster.VectorOfEnumsIsNone():
            if np is None:
                self.vector_of_enums = []
                for i in range(Monster.VectorOfEnumsLength()):
                    self.vector_of_enums.append(Monster.VectorOfEnums(i))
            else:
                self.vector_of_enums = Monster.VectorOfEnumsAsNumpy()
        self.signed_enum = Monster.SignedEnum()
        if not Monster.TestrequirednestedflatbufferIsNone():
            if np is None:
                self.testrequirednestedflatbuffer = []
                for i in range(Monster.TestrequirednestedflatbufferLength()):
                    self.testrequirednestedflatbuffer.append(Monster.Testrequirednestedflatbuffer(i))
            else:
                self.testrequirednestedflatbuffer = Monster.TestrequirednestedflatbufferAsNumpy()
        if not Monster.ScalarKeySortedTablesIsNone():
            self.scalar_key_sorted_tables = []
            for i in range(Monster.ScalarKeySortedTablesLength()):
                if Monster.ScalarKeySortedTables(i) is None:
                    self.scalar_key_sorted_tables.append(None)
                else:
                    stat_ = MyGame.Example.Stat.StatT.InitFromObj(Monster.ScalarKeySortedTables(i))
                    self.scalar_key_sorted_tables.append(stat_)
        if Monster.NativeInline() is not None:
            self.native_inline = MyGame.Example.Test.TestT.InitFromObj(Monster.NativeInline())
        self.long_enum_non_enum_default = Monster.LongEnumNonEnumDefault()
        self.long_enum_normal_default = Monster.LongEnumNormalDefault()
        self.nan_default = Monster.NanDefault()
        self.inf_default = Monster.InfDefault()
        self.positive_inf_default = Monster.PositiveInfDefault()
        self.infinity_default = Monster.InfinityDefault()
        self.positive_infinity_default = Monster.PositiveInfinityDefault()
        self.negative_inf_default = Monster.NegativeInfDefault()
        self.negative_infinity_default = Monster.NegativeInfinityDefault()
        self.double_inf_default = Monster.DoubleInfDefault()

    # MonsterT
    def Pack(self, builder):
        if self.name is not None:
            name = builder.CreateString(self.name)
        if self.inventory is not None:
            if np is not None and type(self.inventory) is np.ndarray:
                inventory = builder.CreateNumpyVector(self.inventory)
            else:
                MonsterStartInventoryVector(builder, len(self.inventory))
                for i in reversed(range(len(self.inventory))):
                    builder.PrependUint8(self.inventory[i])
                inventory = builder.EndVector()
        if self.test is not None:
            test = self.test.Pack(builder)
        if self.test4 is not None:
            MonsterStartTest4Vector(builder, len(self.test4))
            for i in reversed(range(len(self.test4))):
                self.test4[i].Pack(builder)
            test4 = builder.EndVector()
        if self.testarrayofstring is not None:
            testarrayofstringlist = []
            for i in range(len(self.testarrayofstring)):
                testarrayofstringlist.append(builder.CreateString(self.testarrayofstring[i]))
            MonsterStartTestarrayofstringVector(builder, len(self.testarrayofstring))
            for i in reversed(range(len(self.testarrayofstring))):
                builder.PrependUOffsetTRelative(testarrayofstringlist[i])
            testarrayofstring = builder.EndVector()
        if self.testarrayoftables is not None:
            testarrayoftableslist = []
            for i in range(len(self.testarrayoftables)):
                testarrayoftableslist.append(self.testarrayoftables[i].Pack(builder))
            MonsterStartTestarrayoftablesVector(builder, len(self.testarrayoftables))
            for i in reversed(range(len(self.testarrayoftables))):
                builder.PrependUOffsetTRelative(testarrayoftableslist[i])
            testarrayoftables = builder.EndVector()
        if self.enemy is not None:
            enemy = self.enemy.Pack(builder)
        if self.testnestedflatbuffer is not None:
            if np is not None and type(self.testnestedflatbuffer) is np.ndarray:
                testnestedflatbuffer = builder.CreateNumpyVector(self.testnestedflatbuffer)
            else:
                MonsterStartTestnestedflatbufferVector(builder, len(self.testnestedflatbuffer))
                for i in reversed(range(len(self.testnestedflatbuffer))):
                    builder.PrependUint8(self.testnestedflatbuffer[i])
                testnestedflatbuffer = builder.EndVector()
        if self.testempty is not None:
            testempty = self.testempty.Pack(builder)
        if self.testarrayofbools is not None:
            if np is not None and type(self.testarrayofbools) is np.ndarray:
                testarrayofbools = builder.CreateNumpyVector(self.testarrayofbools)
            else:
                MonsterStartTestarrayofboolsVector(builder, len(self.testarrayofbools))
                for i in reversed(range(len(self.testarrayofbools))):
                    builder.PrependBool(self.testarrayofbools[i])
                testarrayofbools = builder.EndVector()
        if self.testarrayofstring2 is not None:
            testarrayofstring2list = []
            for i in range(len(self.testarrayofstring2)):
                testarrayofstring2list.append(builder.CreateString(self.testarrayofstring2[i]))
            MonsterStartTestarrayofstring2Vector(builder, len(self.testarrayofstring2))
            for i in reversed(range(len(self.testarrayofstring2))):
                builder.PrependUOffsetTRelative(testarrayofstring2list[i])
            testarrayofstring2 = builder.EndVector()
        if self.testarrayofsortedstruct is not None:
            MonsterStartTestarrayofsortedstructVector(builder, len(self.testarrayofsortedstruct))
            for i in reversed(range(len(self.testarrayofsortedstruct))):
                self.testarrayofsortedstruct[i].Pack(builder)
            testarrayofsortedstruct = builder.EndVector()
        if self.flex is not None:
            if np is not None and type(self.flex) is np.ndarray:
                flex = builder.CreateNumpyVector(self.flex)
            else:
                MonsterStartFlexVector(builder, len(self.flex))
                for i in reversed(range(len(self.flex))):
                    builder.PrependUint8(self.flex[i])
                flex = builder.EndVector()
        if self.test5 is not None:
            MonsterStartTest5Vector(builder, len(self.test5))
            for i in reversed(range(len(self.test5))):
                self.test5[i].Pack(builder)
            test5 = builder.EndVector()
        if self.vector_of_longs is not None:
            if np is not None and type(self.vector_of_longs) is np.ndarray:
                vector_of_longs = builder.CreateNumpyVector(self.vector_of_longs)
            else:
                MonsterStartVectorOfLongsVector(builder, len(self.vector_of_longs))
                for i in reversed(range(len(self.vector_of_longs))):
                    builder.PrependInt64(self.vector_of_longs[i])
                vector_of_longs = builder.EndVector()
        if self.vector_of_doubles is not None:
            if np is not None and type(self.vector_of_doubles) is np.ndarray:
                vector_of_doubles = builder.CreateNumpyVector(self.vector_of_doubles)
            else:
                MonsterStartVectorOfDoublesVector(builder, len(self.vector_of_doubles))
                for i in reversed(range(len(self.vector_of_doubles))):
                    builder.PrependFloat64(self.vector_of_doubles[i])
                vector_of_doubles = builder.EndVector()
        if self.parent_namespace_test is not None:
            parent_namespace_test = self.parent_namespace_test.Pack(builder)
        if self.vector_of_referrables is not None:
            vector_of_referrableslist = []
            for i in range(len(self.vector_of_referrables)):
                vector_of_referrableslist.append(self.vector_of_referrables[i].Pack(builder))
            MonsterStartVectorOfReferrablesVector(builder, len(self.vector_of_referrables))
            for i in reversed(range(len(self.vector_of_referrables))):
                builder.PrependUOffsetTRelative(vector_of_referrableslist[i])
            vector_of_referrables = builder.EndVector()
        if self.vector_of_weak_references is not None:
            if np is not None and type(self.vector_of_weak_references) is np.ndarray:
                vector_of_weak_references = builder.CreateNumpyVector(self.vector_of_weak_references)
            else:
                MonsterStartVectorOfWeakReferencesVector(builder, len(self.vector_of_weak_references))
                for i in reversed(range(len(self.vector_of_weak_references))):
                    builder.PrependUint64(self.vector_of_weak_references[i])
                vector_of_weak_references = builder.EndVector()
        if self.vector_of_strong_referrables is not None:
            vector_of_strong_referrableslist = []
            for i in range(len(self.vector_of_strong_referrables)):
                vector_of_strong_referrableslist.append(self.vector_of_strong_referrables[i].Pack(builder))
            MonsterStartVectorOfStrongReferrablesVector(builder, len(self.vector_of_strong_referrables))
            for i in reversed(range(len(self.vector_of_strong_referrables))):
                builder.PrependUOffsetTRelative(vector_of_strong_referrableslist[i])
            vector_of_strong_referrables = builder.EndVector()
        if self.vector_of_co_owning_references is not None:
            if np is not None and type(self.vector_of_co_owning_references) is np.ndarray:
                vector_of_co_owning_references = builder.CreateNumpyVector(self.vector_of_co_owning_references)
            else:
                MonsterStartVectorOfCoOwningReferencesVector(builder, len(self.vector_of_co_owning_references))
                for i in reversed(range(len(self.vector_of_co_owning_references))):
                    builder.PrependUint64(self.vector_of_co_owning_references[i])
                vector_of_co_owning_references = builder.EndVector()
        if self.vector_of_non_owning_references is not None:
            if np is not None and type(self.vector_of_non_owning_references) is np.ndarray:
                vector_of_non_owning_references = builder.CreateNumpyVector(self.vector_of_non_owning_references)
            else:
                MonsterStartVectorOfNonOwningReferencesVector(builder, len(self.vector_of_non_owning_references))
                for i in reversed(range(len(self.vector_of_non_owning_references))):
                    builder.PrependUint64(self.vector_of_non_owning_references[i])
                vector_of_non_owning_references = builder.EndVector()
        if self.any_unique is not None:
            any_unique = self.any_unique.Pack(builder)
        if self.any_ambiguous is not None:
            any_ambiguous = self.any_ambiguous.Pack(builder)
        if self.vector_of_enums is not None:
            if np is not None and type(self.vector_of_enums) is np.ndarray:
                vector_of_enums = builder.CreateNumpyVector(self.vector_of_enums)
            else:
                MonsterStartVectorOfEnumsVector(builder, len(self.vector_of_enums))
                for i in reversed(range(len(self.vector_of_enums))):
                    builder.PrependUint8(self.vector_of_enums[i])
                vector_of_enums = builder.EndVector()
        if self.testrequirednestedflatbuffer is not None:
            if np is not None and type(self.testrequirednestedflatbuffer) is np.ndarray:
                testrequirednestedflatbuffer = builder.CreateNumpyVector(self.testrequirednestedflatbuffer)
            else:
                MonsterStartTestrequirednestedflatbufferVector(builder, len(self.testrequirednestedflatbuffer))
                for i in reversed(range(len(self.testrequirednestedflatbuffer))):
                    builder.PrependUint8(self.testrequirednestedflatbuffer[i])
                testrequirednestedflatbuffer = builder.EndVector()
        if self.scalar_key_sorted_tables is not None:
            scalar_key_sorted_tableslist = []
            for i in range(len(self.scalar_key_sorted_tables)):
                scalar_key_sorted_tableslist.append(self.scalar_key_sorted_tables[i].Pack(builder))
            MonsterStartScalarKeySortedTablesVector(builder, len(self.scalar_key_sorted_tables))
            for i in reversed(range(len(self.scalar_key_sorted_tables))):
                builder.PrependUOffsetTRelative(scalar_key_sorted_tableslist[i])
            scalar_key_sorted_tables = builder.EndVector()
        MonsterStart(builder)
        if self.pos is not None:
            pos = self.pos.Pack(builder)
            MonsterAddPos(builder, pos)
        MonsterAddMana(builder, self.mana)
        MonsterAddHp(builder, self.hp)
        if self.name is not None:
            MonsterAddName(builder, name)
        if self.inventory is not None:
            MonsterAddInventory(builder, inventory)
        MonsterAddColor(builder, self.color)
        MonsterAddTestType(builder, self.testType)
        if self.test is not None:
            MonsterAddTest(builder, test)
        if self.test4 is not None:
            MonsterAddTest4(builder, test4)
        if self.testarrayofstring is not None:
            MonsterAddTestarrayofstring(builder, testarrayofstring)
        if self.testarrayoftables is not None:
            MonsterAddTestarrayoftables(builder, testarrayoftables)
        if self.enemy is not None:
            MonsterAddEnemy(builder, enemy)
        if self.testnestedflatbuffer is not None:
            MonsterAddTestnestedflatbuffer(builder, testnestedflatbuffer)
        if self.testempty is not None:
            MonsterAddTestempty(builder, testempty)
        MonsterAddTestbool(builder, self.testbool)
        MonsterAddTesthashs32Fnv1(builder, self.testhashs32_fnv1)
        MonsterAddTesthashu32Fnv1(builder, self.testhashu32_fnv1)
        MonsterAddTesthashs64Fnv1(builder, self.testhashs64_fnv1)
        MonsterAddTesthashu64Fnv1(builder, self.testhashu64_fnv1)
        MonsterAddTesthashs32Fnv1a(builder, self.testhashs32_fnv1a)
        MonsterAddTesthashu32Fnv1a(builder, self.testhashu32_fnv1a)
        MonsterAddTesthashs64Fnv1a(builder, self.testhashs64_fnv1a)
        MonsterAddTesthashu64Fnv1a(builder, self.testhashu64_fnv1a)
        if self.testarrayofbools is not None:
            MonsterAddTestarrayofbools(builder, testarrayofbools)
        MonsterAddTestf(builder, self.testf)
        MonsterAddTestf2(builder, self.testf2)
        MonsterAddTestf3(builder, self.testf3)
        if self.testarrayofstring2 is not None:
            MonsterAddTestarrayofstring2(builder, testarrayofstring2)
        if self.testarrayofsortedstruct is not None:
            MonsterAddTestarrayofsortedstruct(builder, testarrayofsortedstruct)
        if self.flex is not None:
            MonsterAddFlex(builder, flex)
        if self.test5 is not None:
            MonsterAddTest5(builder, test5)
        if self.vector_of_longs is not None:
            MonsterAddVectorOfLongs(builder, vector_of_longs)
        if self.vector_of_doubles is not None:
            MonsterAddVectorOfDoubles(builder, vector_of_doubles)
        if self.parent_namespace_test is not None:
            MonsterAddParentNamespaceTest(builder, parent_namespace_test)
        if self.vector_of_referrables is not None:
            MonsterAddVectorOfReferrables(builder, vector_of_referrables)
        MonsterAddSingleWeakReference(builder, self.single_weak_reference)
        if self.vector_of_weak_references is not None:
            MonsterAddVectorOfWeakReferences(builder, vector_of_weak_references)
        if self.vector_of_strong_referrables is not None:
            MonsterAddVectorOfStrongReferrables(builder, vector_of_strong_referrables)
        MonsterAddCoOwningReference(builder, self.co_owning_reference)
        if self.vector_of_co_owning_references is not None:
            MonsterAddVectorOfCoOwningReferences(builder, vector_of_co_owning_references)
        MonsterAddNonOwningReference(builder, self.non_owning_reference)
        if self.vector_of_non_owning_references is not None:
            MonsterAddVectorOfNonOwningReferences(builder, vector_of_non_owning_references)
        MonsterAddAnyUniqueType(builder, self.anyUniqueType)
        if self.any_unique is not None:
            MonsterAddAnyUnique(builder, any_unique)
        MonsterAddAnyAmbiguousType(builder, self.anyAmbiguousType)
        if self.any_ambiguous is not None:
            MonsterAddAnyAmbiguous(builder, any_ambiguous)
        if self.vector_of_enums is not None:
            MonsterAddVectorOfEnums(builder, vector_of_enums)
        MonsterAddSignedEnum(builder, self.signed_enum)
        if self.testrequirednestedflatbuffer is not None:
            MonsterAddTestrequirednestedflatbuffer(builder, testrequirednestedflatbuffer)
        if self.scalar_key_sorted_tables is not None:
            MonsterAddScalarKeySortedTables(builder, scalar_key_sorted_tables)
        if self.native_inline is not None:
            native_inline = self.native_inline.Pack(builder)
            MonsterAddNativeInline(builder, native_inline)
        MonsterAddLongEnumNonEnumDefault(builder, self.long_enum_non_enum_default)
        MonsterAddLongEnumNormalDefault(builder, self.long_enum_normal_default)
        MonsterAddNanDefault(builder, self.nan_default)
        MonsterAddInfDefault(builder, self.inf_default)
        MonsterAddPositiveInfDefault(builder, self.positive_inf_default)
        MonsterAddInfinityDefault(builder, self.infinity_default)
        MonsterAddPositiveInfinityDefault(builder, self.positive_infinity_default)
        MonsterAddNegativeInfDefault(builder, self.negative_inf_default)
        MonsterAddNegativeInfinityDefault(builder, self.negative_infinity_default)
        MonsterAddDoubleInfDefault(builder, self.double_inf_default)
        Monster = MonsterEnd(builder)
        return Monster
