// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;

pub enum LeafOffset {}

#[derive(Copy, Clone, PartialEq)]
pub struct Leaf<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Leaf<'a> {
    type Inner = Leaf<'a>;

    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
    }
}

impl<'a> Leaf<'a> {
    pub const VT_SECRET: ::flatbuffers::VOffsetT = 4;
    pub const VT_PIN: ::flatbuffers::VOffsetT = 6;

    pub const fn get_fully_qualified_name() -> &'static str {
        "EncryptionV3.Leaf"
    }

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        Leaf { _tab: table }
    }

    /// Field-encryption format 3 walk program of Leaf (see
    /// flatbuffers_encryption).
    pub const FLATBUFFERS_ENCRYPTION_PROGRAM: &'static [u32] = &[
        1, 2, 2, 0, 6, 4, 1, 4,
    ];

    /// Encrypts, in place, the (encrypted) fields of a Leaf buffer with
    /// field-encryption format 3 (key: 32 bytes; record_index: unique per buffer
    /// under the key). On an error no byte has changed.
    pub fn encrypt_buffer(buf: &mut [u8], key: &[u8], record_index: u32) -> Result<(), super::super::flatbuffers_encryption::Error> {
        super::super::flatbuffers_encryption::crypt_buffer(buf, key, record_index, Self::FLATBUFFERS_ENCRYPTION_PROGRAM)
    }

    /// Decrypts, in place, the (encrypted) fields of a Leaf buffer with
    /// field-encryption format 3 (key: 32 bytes; record_index: unique per buffer
    /// under the key). On an error no byte has changed.
    pub fn decrypt_buffer(buf: &mut [u8], key: &[u8], record_index: u32) -> Result<(), super::super::flatbuffers_encryption::Error> {
        super::super::flatbuffers_encryption::crypt_buffer(buf, key, record_index, Self::FLATBUFFERS_ENCRYPTION_PROGRAM)
    }

    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args LeafArgs<'args>
    ) -> ::flatbuffers::WIPOffset<Leaf<'bldr>> {
        let mut builder = LeafBuilder::new(_fbb);
        builder.add_pin(args.pin);
        if let Some(x) = args.secret { builder.add_secret(x); }
        builder.finish()
    }

    pub fn unpack(&self) -> LeafT {
        let secret = self.secret().map(|x| {
            alloc::string::ToString::to_string(x)
        });
        let pin = self.pin();
        LeafT {
            secret,
            pin,
        }
    }

    #[inline]
    pub fn secret(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Leaf::VT_SECRET, None)}
    }

    #[inline]
    pub fn pin(&self) -> u32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe { self._tab.get::<u32>(Leaf::VT_PIN, Some(0)).unwrap()}
    }
}

impl ::flatbuffers::Verifiable for Leaf<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier, pos: usize
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("secret", Self::VT_SECRET, false)?
            .visit_field::<u32>("pin", Self::VT_PIN, false)?
            .finish();
        Ok(())
    }
}

pub struct LeafArgs<'a> {
    pub secret: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub pin: u32,
}

impl<'a> Default for LeafArgs<'a> {
    #[inline]
    fn default() -> Self {
        LeafArgs {
            secret: None,
            pin: 0,
        }
    }
}

pub struct LeafBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}

impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> LeafBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_secret(&mut self, secret: ::flatbuffers::WIPOffset<&'b  str>) {
        self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Leaf::VT_SECRET, secret);
    }

    #[inline]
    pub fn add_pin(&mut self, pin: u32) {
        self.fbb_.push_slot::<u32>(Leaf::VT_PIN, pin, 0);
    }

    #[inline]
    pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> LeafBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        LeafBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }

    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<Leaf<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for Leaf<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("Leaf");
        ds.field("secret", &self.secret());
        ds.field("pin", &self.pin());
        ds.finish()
    }
}

#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct LeafT {
    pub secret: Option<alloc::string::String>,
    pub pin: u32,
}

impl Default for LeafT {
    fn default() -> Self {
        Self {
            secret: None,
            pin: 0,
        }
    }
}

impl LeafT {
    pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
        &self,
        _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>
    ) -> ::flatbuffers::WIPOffset<Leaf<'b>> {
        let secret = self.secret.as_ref().map(|x|{
            _fbb.create_string(x)
        });
        let pin = self.pin;
        Leaf::create(_fbb, &LeafArgs{
            secret,
            pin,
        })
    }
}
