name: Publish flatc-wasm to NPM

on:
  push:
    tags:
      - "wasm-v*"
  workflow_dispatch:

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-24.04
    env:
      EMSDK_DIR: ${{ runner.temp }}/emsdk
      EMSDK_VERSION: "3.1.74"
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org/"

      - name: Setup Emscripten
        run: |
          git clone --branch "${EMSDK_VERSION}" --depth 1 https://github.com/emscripten-core/emsdk.git "${EMSDK_DIR}"
          cd "${EMSDK_DIR}"
          ./emsdk install "${EMSDK_VERSION}"
          ./emsdk activate "${EMSDK_VERSION}"

      - name: Configure and Build
        run: |
          source "${EMSDK_DIR}/emsdk_env.sh"
          emcmake cmake -B build/wasm -S . -DCMAKE_BUILD_TYPE=Release -DFLATBUFFERS_BUILD_WASM=ON -DFLATBUFFERS_WASM_ENABLE_HE=ON
          cmake --build build/wasm --parallel $(nproc) --target flatc_wasm_npm

      - name: Install dependencies
        run: npm install --ignore-scripts
        working-directory: wasm

      - name: Test package
        run: npm test
        working-directory: wasm

      - name: Publish
        run: npm publish --access public --provenance --tag latest --ignore-scripts
        working-directory: wasm
